import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.howItWorks': 'How It Works',
    'nav.humanGuided': 'Our Approach',
    'nav.services': 'Plans',
    'nav.labs': 'Coming Soon',
    'nav.login': 'Login',
    'nav.getStarted': 'Get Started Free',
    'nav.theme': 'Theme',
    'nav.sla': 'Service Agreement',
    
    // Hero
    'hero.headline': 'Your Website.',
    'hero.headlineAccent': 'Our Expertise.',
    'hero.subheadline': 'We build beautiful, professional websites for people who don\'t want to deal with technology. You talk to a real person. We handle everything else — completely free to start.',
    'hero.cta.primary': 'Talk to Us — It\'s Free',
    'hero.cta.secondary': 'See How It Works',
    'hero.badge': 'Built for people, not techies',
    'hero.input.placeholder': 'Describe your website idea in one sentence...',
    'hero.input.submit': 'Continue',
    'hero.input.examples': 'Examples',
    'hero.trust.noCard': 'No credit card required',
    'hero.trust.human': 'Real human support',
    'hero.trust.free': 'Start for free',
    
    // Example ideas
    'example.clinic': 'Website for my clinic',
    'example.nonprofit': 'Website for a non-profit organization',
    'example.business': 'Landing page for my business',
    
    // Path Options
    'paths.back': 'Change my idea',
    'paths.yourIdea': 'Your idea',
    'paths.recommendation': 'Based on your idea, we recommend',
    'paths.recommended': 'Recommended',
    'paths.select': 'Choose This Option',
    'paths.promise': 'First version delivered within 24 hours',
    'paths.chat.title': 'Talk to a Human',
    'paths.chat.desc': 'Chat with a real person right now. We\'ll help you figure out exactly what you need.',
    'paths.chat.badge': 'Immediate',
    'paths.meeting.title': 'Schedule a Meeting',
    'paths.meeting.desc': 'Book a video call within 48 hours. Perfect for detailed discussions about your project.',
    'paths.meeting.badge': 'Within 48h',
    'paths.questions.title': 'Quick Questions',
    'paths.questions.desc': 'Answer a few simple questions and we\'ll start building. The fastest way to get your website.',
    'paths.questions.badge': 'Ready in 24h',
    
    // Human Guided Section
    'humanGuided.title': 'You don\'t need to understand technology. We do.',
    'humanGuided.subtitle': 'Whether you\'re a small business, a non-profit, or just someone with an idea — we\'re here to help. No jargon. No confusion. Just friendly, human support.',
    'humanGuided.human.title': 'Always Human',
    'humanGuided.human.desc': 'You\'ll never talk to a robot. A real person guides you every step of the way.',
    'humanGuided.manager.title': 'Your Account Manager',
    'humanGuided.manager.desc': 'Every customer gets a dedicated human contact who knows your project inside and out.',
    'humanGuided.worry.title': 'Zero Worries',
    'humanGuided.worry.desc': 'We handle hosting, security, updates, and all the technical stuff. You focus on your business.',
    'humanGuided.support.title': 'We\'re Here to Help',
    'humanGuided.support.desc': 'Have a question? Need a change? Just ask. We respond quickly and kindly.',
    'humanGuided.quote': 'You talk to a human. We handle everything else.',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Getting your website is simple. We guide you through every step.',
    'howItWorks.step1.title': 'Tell Us Your Idea',
    'howItWorks.step1.desc': 'Share what you need — a website for your business, organization, or project. No technical knowledge required.',
    'howItWorks.step2.title': 'We Guide You',
    'howItWorks.step2.desc': 'Your account manager helps you make simple choices about design and content. We explain everything in plain language.',
    'howItWorks.step3.title': 'We Build It For You',
    'howItWorks.step3.desc': 'Our team creates your website with care. You just approve the results — no work on your end.',
    'howItWorks.step4.title': 'Ongoing Support',
    'howItWorks.step4.desc': 'Your site stays online, secure, and updated. Need changes? Just ask your account manager.',
    
    // How It Works Page
    'hiw.title': 'How It Works',
    'hiw.subtitle': 'Getting your website is simple. We guide you through every step — no technical knowledge needed.',
    'hiw.promise': 'First version delivered within 24 hours',
    'hiw.step1.title': 'Choose Your Domain',
    'hiw.step1.desc': 'Pick a name for your website. We\'ll check if it\'s available and handle the registration for you.',
    'hiw.step2.title': 'Answer a Few Questions',
    'hiw.step2.desc': 'Tell us about your business and what you\'d like your website to do. Just simple questions, no technical stuff.',
    'hiw.step3.title': 'We Build Your Website',
    'hiw.step3.desc': 'Our team creates a beautiful, professional website based on your answers. You\'ll see the first version within 24 hours.',
    'hiw.step4.title': 'Review & Go Live',
    'hiw.step4.desc': 'Check out your new website and let us know if you\'d like any changes. Once you\'re happy, we publish it for the world to see.',
    'hiw.step5.title': 'Ongoing Human Support',
    'hiw.step5.desc': 'Need changes? Have questions? Your dedicated account manager is always here to help.',
    'hiw.included.title': 'What\'s Included',
    'hiw.included.item1': 'Beautiful, professional website design',
    'hiw.included.item2': 'Free hosting — forever',
    'hiw.included.item3': 'Security and updates included',
    'hiw.included.item4': 'Your own account manager',
    'hiw.included.item5': 'Mobile-friendly design',
    'hiw.included.item6': 'Basic SEO setup',
    'hiw.cta.title': 'Ready to Get Started?',
    'hiw.cta.subtitle': 'Describe your idea and we\'ll guide you through the rest.',
    'hiw.cta.button': 'Start Now — It\'s Free',
    
    // SLA Page
    'sla.title': 'Service Agreement',
    'sla.subtitle': 'Clear, honest terms. We want you to know exactly what to expect from us.',
    'sla.response.title': 'Response Times',
    'sla.response.item1': 'Email inquiries: We respond within 24 hours on business days',
    'sla.response.item2': 'Urgent issues: Priority response within 4 hours',
    'sla.response.item3': 'Chat support: Real-time during business hours (9 AM - 6 PM CET)',
    'sla.changes.title': 'Change Requests',
    'sla.changes.item1': 'Starter plan: 2 changes per month included',
    'sla.changes.item2': 'Pro plan: Unlimited changes included',
    'sla.changes.item3': 'Most changes are completed within 48 hours',
    'sla.scope.title': 'What\'s Covered',
    'sla.scope.item1': 'Website hosting and maintenance',
    'sla.scope.item2': 'Security updates and backups',
    'sla.scope.item3': 'Content updates (text, images, basic layout)',
    'sla.scope.item4': 'Technical support and troubleshooting',
    'sla.limits.title': 'Good to Know',
    'sla.limits.item1': 'Major redesigns may require additional discussion',
    'sla.limits.item2': 'Complex features (e-commerce, booking systems) require Pro plan',
    'sla.limits.item3': 'We don\'t store sensitive data like passwords or payment info',
    'sla.promise.title': 'Our Promise',
    'sla.promise.desc': 'We\'re here to make your life easier, not harder. If something isn\'t working, we\'ll fix it. If you\'re confused, we\'ll explain. You\'ll always talk to a real human who cares about your success.',
    
    // Services / Pricing
    'services.title': 'Simple, Honest Pricing',
    'services.subtitle': 'Start completely free. Upgrade only if you need more.',
    'services.starter.title': 'Starter',
    'services.starter.price': '$0.99',
    'services.starter.period': '/month',
    'services.starter.feature1': 'Beautiful, professional website',
    'services.starter.feature2': '2 changes per month',
    'services.starter.feature3': 'Human support included',
    'services.starter.feature4': 'Hosting included',
    'services.starter.feature5': 'Maintenance included',
    'services.starter.cta': 'Get Started',
    'services.pro.title': 'Pro',
    'services.pro.price': '$4.99',
    'services.pro.period': '/month',
    'services.pro.feature1': 'Everything in Starter',
    'services.pro.feature2': 'Unlimited changes',
    'services.pro.feature3': 'Priority human support',
    'services.pro.feature4': 'Hosting included',
    'services.pro.feature5': 'Maintenance included',
    'services.pro.cta': 'Upgrade to Pro',
    'services.free.title': 'Free Forever',
    'services.free.price': '$0',
    'services.free.period': '/month',
    'services.free.feature1': 'Beautiful, professional website',
    'services.free.feature2': 'Free hosting — always',
    'services.free.feature3': 'Security and updates included',
    'services.free.feature4': 'Your own account manager',
    'services.free.feature5': 'Friendly email support',
    'services.free.cta': 'Get Started Free',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '$49',
    'services.concierge.period': '/month',
    'services.concierge.feature1': 'Everything in Free',
    'services.concierge.feature2': 'Unlimited website changes',
    'services.concierge.feature3': 'Priority phone & chat support',
    'services.concierge.feature4': 'Advanced features on request',
    'services.concierge.feature5': 'Custom integrations',
    'services.concierge.cta': 'Upgrade to Concierge',
    
    // Labs
    'labs.title': 'Coming Soon',
    'labs.subtitle': 'We\'re always improving. Here\'s what\'s next.',
    'labs.ai.title': 'Smarter Suggestions',
    'labs.ai.desc': 'We\'ll help you with design ideas and content tips — powered by smart technology, delivered by humans.',
    'labs.deploy.title': 'Faster & More Reliable',
    'labs.deploy.desc': 'Your website will load even faster and stay online no matter what.',
    'labs.coming': 'In Development',
    
    // CTA
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Talk to a real person today. Your website could be live this week — and it\'s free.',
    'cta.button': 'Let\'s Talk — It\'s Free',
    
    // Auth
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to manage your website requests',
    'auth.login.button': 'Sign In',
    'auth.signup.title': 'Create Account',
    'auth.signup.subtitle': 'Join us to start building your website',
    'auth.signup.button': 'Create Account',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': '••••••••',
    'auth.loading': 'Please wait...',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.signupLink': 'Create one',
    'auth.loginLink': 'Sign in',
    'auth.success.login': 'Welcome back!',
    'auth.success.loginDesc': 'You have successfully signed in.',
    'auth.success.signup': 'Account created!',
    'auth.success.signupDesc': 'Welcome to Aureka Web. You can now submit your website request.',
    'auth.error.title': 'Something went wrong',
    'auth.error.alreadyRegistered': 'This email is already registered. Please sign in instead.',
    
    // Dashboard
    'dashboard.loading': 'Loading...',
    'dashboard.welcome': 'Your Dashboard',
    'dashboard.newRequest': 'New Website Request',
    'dashboard.logout': 'Sign Out',
    'dashboard.empty.title': 'No Website Requests Yet',
    'dashboard.empty.desc': 'Ready to get your first website? Click below to start — it only takes a few minutes.',
    'dashboard.empty.cta': 'Create My First Website',
    'dashboard.status.pending': 'Pending Review',
    'dashboard.status.inProgress': 'In Progress',
    'dashboard.status.complete': 'Complete',
    
    // Request Form
    'request.step': 'Step',
    'request.promise': 'Ready in 24 hours',
    'request.yourIdea': 'Your website idea',
    'request.step1.title': 'Tell Us About Yourself',
    'request.step2.title': 'About Your Website',
    'request.step3.title': 'Final Preferences',
    'request.fullName': 'Full Legal Name',
    'request.fullNamePlaceholder': 'John Smith',
    'request.email': 'Email Address',
    'request.emailPlaceholder': 'your@email.com',
    'request.phone': 'Phone Number',
    'request.phonePlaceholder': '+1 234 567 8900',
    'request.entityType': 'You are...',
    'request.entity.individual': 'Individual',
    'request.entity.business': 'Business',
    'request.entity.ngo': 'Non-Profit',
    'request.websiteGoal': 'What should your website do?',
    'request.goal.showcase': 'Showcase my work',
    'request.goal.services': 'List my services',
    'request.goal.contact': 'Let people contact me',
    'request.goal.information': 'Share information',
    'request.preferredLanguage': 'Website Language',
    'request.stylePreference': 'Preferred Style',
    'request.style.modern': 'Modern & Clean',
    'request.style.classic': 'Classic & Elegant',
    'request.style.minimal': 'Minimal & Simple',
    'request.style.colorful': 'Colorful & Fun',
    'request.consent': 'By submitting this request, I confirm that my information is accurate and I agree to pay the required fees after reviewing and receiving my website.',
    'request.back': 'Back',
    'request.next': 'Continue',
    'request.submit': 'Submit Request',
    'request.submitting': 'Submitting...',
    'request.success.title': 'Request Submitted!',
    'request.success.desc': 'We\'ve received your request. Expect your first website version within 24 hours!',
    'request.error.title': 'Something went wrong',
    
    // Plans - Mini Table
    'plans.badge': 'Simple Pricing',
    'plans.title': 'Choose Your Plan',
    'plans.subtitle': 'From free landing pages to complete business systems. No hidden fees.',
    'plans.standard.name': 'Standard',
    'plans.standard.highlight': '1 Change / Month • Free Subdomain',
    'plans.standard.cta': 'Get Started Free',
    'plans.standard.subtitle': 'Perfect for starters',
    'plans.pro.name': 'Pro',
    'plans.pro.highlight': 'Multi-page Website • Weekly Changes',
    'plans.pro.cta': 'Launch Now',
    'plans.pro.subtitle': 'For growing businesses',
    'plans.pro.yearlySaving': 'Save 2 Months',
    'plans.business.name': 'Business',
    'plans.business.highlight': 'Full Systems • Unlimited Changes',
    'plans.business.cta': 'Request Demo',
    'plans.business.subtitle': 'Complete solutions',
    'plans.business.yearlySaving': 'Save $100',
    'plans.popular': 'Most Popular',
    'plans.free': 'Free',
    'plans.month': 'mo',
    'plans.year': 'yr',
    'plans.viewFull': 'View Full Comparison',
    
    // Plans - Full Page
    'plans.pageTitle': 'Complete Pricing & Plans',
    'plans.pageSubtitle': 'Transparent pricing for every stage of your business. Start free, scale when ready.',
    'plans.compareTitle': 'Full Feature Comparison',
    
    // Plans - Table Features
    'plans.table.feature': 'Feature',
    'plans.table.hosting': 'Hosting & Maintenance',
    'plans.table.hostingTip': 'We handle all hosting, security updates, and backups for you.',
    'plans.table.domain': 'Domain Name',
    'plans.table.domainTip': 'Your website address (e.g., yourbusiness.com).',
    'plans.table.domainSetup': 'Domain Setup',
    'plans.table.domainSetupTip': 'How we help you set up your domain.',
    'plans.table.buildType': 'Build Type',
    'plans.table.buildTypeTip': 'The complexity and type of website we build.',
    'plans.table.database': 'Database / System',
    'plans.table.databaseTip': 'Data storage for dynamic content, users, products, etc.',
    'plans.table.delivery': 'Delivery Time',
    'plans.table.deliveryTip': 'Time to receive your first launch-ready version.',
    'plans.table.scaling': 'Scaling (Edits)',
    'plans.table.scalingTip': 'How often you can request changes to your website.',
    'plans.table.support': 'Support Type',
    'plans.table.supportTip': 'How you can reach us for help.',
    'plans.table.response': 'Response Time',
    'plans.table.responseTip': 'How quickly we respond to your requests.',
    'plans.table.monthly': 'Monthly Price',
    'plans.table.yearly': 'Yearly Price',
    
    // Plans - Feature Values
    'plans.features.hostingFree': 'Free Forever',
    'plans.features.hostingDb': 'Free + Database Maintenance',
    'plans.features.hostingFull': 'Free + Full System Maintenance',
    'plans.features.subdomain': 'Free Subdomain',
    'plans.features.customDomain': 'Free Custom Domain',
    'plans.features.domainConnect': 'Connect your own domain',
    'plans.features.domainDone': 'Done-for-you setup',
    'plans.features.landingPage': 'High-Speed Landing Page',
    'plans.features.multiPage': 'Professional Multi-page',
    'plans.features.fullSystem': 'Complex Full Systems',
    'plans.features.na': 'N/A',
    'plans.features.db5k': 'Up to 5,000 entries / 1 GB',
    'plans.features.db50k': 'Up to 50,000 entries / Full Scale',
    'plans.features.delivery48h': '48 Hours to Launch',
    'plans.features.delivery5d': '48h standard / 5 days complex',
    'plans.features.scaling1': '1 Change / Month',
    'plans.features.scalingWeek': '1 Change / Week',
    'plans.features.scalingUnlimited': 'Unlimited Changes',
    'plans.features.supportEmail': 'Email & Chat',
    'plans.features.supportVideo': 'Email, Chat & Video Meetings',
    'plans.features.supportDedicated': 'Dedicated Manager + All Channels',
    'plans.features.response2d': '2 Business Days',
    'plans.features.response1d': '1 Business Day',
    'plans.features.responseSameDay': 'Same Day / Priority',
    
    // Add-ons
    'addons.title': 'Premium Add-ons',
    'addons.subtitle': 'Enhance your website with professional services.',
    'addons.seo': 'AUREKA SEO Boost',
    'addons.copywriting': 'Professional Copywriting',
    'addons.speedAudit': 'Speed & Performance Audit',
    'addons.branding': 'Logo & Branding Kit',
    'addons.social': 'Social Media Integration',
    'addons.analytics': 'Analytics & Conversion Setup',
    'addons.extraPage': 'Extra Page / Feature',
    'addons.prioritySupport': 'Priority Support Upgrade',
    'addons.landingPage': 'Marketing Landing Page',
    'addons.perPage': '/page',
    'addons.perSite': '/site',
    'addons.oneTime': 'one-time',
    'addons.freeProBusiness': 'Free in Pro/Business',
    
    // Anti-DIY Philosophy
    'plans.antiDiy.title': 'Stop Fighting with Drag-and-Drop Builders',
    'plans.antiDiy.desc': 'At AUREKA WEB, we provide Human-Centered Support. You send the request, we deliver the Launch-Ready Version in 48 hours. No hassle, no learning curve, just results.',
    'plans.antiDiy.delivery': '48h Delivery',
    'plans.antiDiy.support': 'Human Support',
    'plans.versionNote': 'Production-ready & scalable',
    
    // Plans CTA
    'plans.cta.title': 'Ready to Get Started?',
    'plans.cta.subtitle': 'Tell us about your project and we\'ll handle the rest. First version in 48 hours.',
    'plans.cta.button': 'Start Your Website Now',
    
    // Footer
    'footer.tagline': 'Websites made simple. Support made human.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2025 Aureka Solutions. All rights reserved.',
    'footer.ideal': 'Perfect for small businesses, non-profits, and anyone who wants a great website without the hassle.',
  },
  ar: {
    // Navigation
    'nav.howItWorks': 'كيف يعمل',
    'nav.humanGuided': 'نهجنا',
    'nav.services': 'الباقات',
    'nav.labs': 'قريباً',
    'nav.login': 'تسجيل الدخول',
    'nav.getStarted': 'ابدأ مجاناً',
    'nav.theme': 'المظهر',
    'nav.sla': 'اتفاقية الخدمة',
    
    // Hero
    'hero.headline': 'موقعك.',
    'hero.headlineAccent': 'خبرتنا.',
    'hero.subheadline': 'نبني مواقع احترافية وجميلة للأشخاص الذين لا يريدون التعامل مع التقنية. تتحدث مع شخص حقيقي. نحن نتولى كل شيء آخر — البداية مجانية تماماً.',
    'hero.cta.primary': 'تحدث معنا — مجاناً',
    'hero.cta.secondary': 'شاهد كيف يعمل',
    'hero.badge': 'مصمم للناس، لا للتقنيين',
    'hero.input.placeholder': 'صف فكرة موقعك في جملة واحدة...',
    'hero.input.submit': 'متابعة',
    'hero.input.examples': 'أمثلة',
    'hero.trust.noCard': 'بدون بطاقة ائتمان',
    'hero.trust.human': 'دعم بشري حقيقي',
    'hero.trust.free': 'ابدأ مجاناً',
    
    // Example ideas
    'example.clinic': 'موقع لعيادتي',
    'example.nonprofit': 'موقع لمؤسسة خيرية',
    'example.business': 'صفحة هبوط لعملي',
    
    // Path Options
    'paths.back': 'تغيير فكرتي',
    'paths.yourIdea': 'فكرتك',
    'paths.recommendation': 'بناءً على فكرتك، نوصي بـ',
    'paths.recommended': 'موصى به',
    'paths.select': 'اختر هذا الخيار',
    'paths.promise': 'النسخة الأولى خلال 24 ساعة',
    'paths.chat.title': 'تحدث مع إنسان',
    'paths.chat.desc': 'تحدث مع شخص حقيقي الآن. سنساعدك لمعرفة ما تحتاجه بالضبط.',
    'paths.chat.badge': 'فوري',
    'paths.meeting.title': 'حجز اجتماع',
    'paths.meeting.desc': 'احجز مكالمة فيديو خلال 48 ساعة. مثالي للنقاشات التفصيلية.',
    'paths.meeting.badge': 'خلال 48 ساعة',
    'paths.questions.title': 'أسئلة سريعة',
    'paths.questions.desc': 'أجب عن بعض الأسئلة البسيطة وسنبدأ البناء. أسرع طريقة للحصول على موقعك.',
    'paths.questions.badge': 'جاهز في 24 ساعة',
    
    // Human Guided Section
    'humanGuided.title': 'لا تحتاج لفهم التقنية. نحن نفهمها.',
    'humanGuided.subtitle': 'سواء كنت شركة صغيرة أو مؤسسة خيرية أو شخصاً لديه فكرة — نحن هنا لمساعدتك. بدون مصطلحات معقدة. بدون ارتباك. فقط دعم بشري ودود.',
    'humanGuided.human.title': 'دائماً بشري',
    'humanGuided.human.desc': 'لن تتحدث أبداً مع روبوت. شخص حقيقي يرشدك في كل خطوة.',
    'humanGuided.manager.title': 'مدير حسابك',
    'humanGuided.manager.desc': 'كل عميل يحصل على شخص مخصص يعرف مشروعك تماماً.',
    'humanGuided.worry.title': 'بدون قلق',
    'humanGuided.worry.desc': 'نتولى الاستضافة والأمان والتحديثات وكل الأمور التقنية. ركز على عملك.',
    'humanGuided.support.title': 'نحن هنا للمساعدة',
    'humanGuided.support.desc': 'لديك سؤال؟ تحتاج تغيير؟ فقط اسأل. نرد بسرعة ولطف.',
    'humanGuided.quote': 'تتحدث مع إنسان. نحن نتولى كل شيء آخر.',
    
    // How It Works
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.subtitle': 'الحصول على موقعك سهل. نرشدك في كل خطوة.',
    'howItWorks.step1.title': 'أخبرنا بفكرتك',
    'howItWorks.step1.desc': 'شارك ما تحتاجه — موقع لعملك أو مؤسستك أو مشروعك. لا تحتاج معرفة تقنية.',
    'howItWorks.step2.title': 'نرشدك',
    'howItWorks.step2.desc': 'مدير حسابك يساعدك في اختيارات بسيطة للتصميم والمحتوى. نشرح كل شيء بلغة واضحة.',
    'howItWorks.step3.title': 'نبنيه لك',
    'howItWorks.step3.desc': 'فريقنا يصنع موقعك بعناية. أنت فقط توافق على النتائج — بدون عمل من طرفك.',
    'howItWorks.step4.title': 'دعم مستمر',
    'howItWorks.step4.desc': 'موقعك يبقى متاحاً وآمناً ومحدثاً. تحتاج تغييرات؟ فقط اسأل مدير حسابك.',
    
    // How It Works Page
    'hiw.title': 'كيف يعمل',
    'hiw.subtitle': 'الحصول على موقعك سهل. نرشدك في كل خطوة — بدون معرفة تقنية.',
    'hiw.promise': 'النسخة الأولى خلال 24 ساعة',
    'hiw.step1.title': 'اختر نطاقك',
    'hiw.step1.desc': 'اختر اسماً لموقعك. سنتحقق من توفره ونتولى التسجيل نيابة عنك.',
    'hiw.step2.title': 'أجب عن بعض الأسئلة',
    'hiw.step2.desc': 'أخبرنا عن عملك وما تريده من موقعك. أسئلة بسيطة فقط، بدون تعقيدات تقنية.',
    'hiw.step3.title': 'نبني موقعك',
    'hiw.step3.desc': 'فريقنا يصنع موقعاً جميلاً واحترافياً بناءً على إجاباتك. ستراه خلال 24 ساعة.',
    'hiw.step4.title': 'راجع وانطلق',
    'hiw.step4.desc': 'راجع موقعك الجديد وأخبرنا إذا أردت أي تعديلات. بمجرد رضاك، ننشره للعالم.',
    'hiw.step5.title': 'دعم بشري مستمر',
    'hiw.step5.desc': 'تحتاج تغييرات؟ لديك أسئلة؟ مدير حسابك دائماً هنا للمساعدة.',
    'hiw.included.title': 'ما المشمول',
    'hiw.included.item1': 'تصميم موقع جميل واحترافي',
    'hiw.included.item2': 'استضافة مجانية — للأبد',
    'hiw.included.item3': 'الأمان والتحديثات مشمولة',
    'hiw.included.item4': 'مدير حساب خاص بك',
    'hiw.included.item5': 'تصميم متوافق مع الجوال',
    'hiw.included.item6': 'إعداد SEO أساسي',
    'hiw.cta.title': 'مستعد للبدء؟',
    'hiw.cta.subtitle': 'صف فكرتك وسنرشدك في الباقي.',
    'hiw.cta.button': 'ابدأ الآن — مجاناً',
    
    // SLA Page
    'sla.title': 'اتفاقية الخدمة',
    'sla.subtitle': 'شروط واضحة وصادقة. نريدك أن تعرف بالضبط ما تتوقعه منا.',
    'sla.response.title': 'أوقات الاستجابة',
    'sla.response.item1': 'الاستفسارات عبر البريد: نرد خلال 24 ساعة في أيام العمل',
    'sla.response.item2': 'المشاكل العاجلة: رد أولوية خلال 4 ساعات',
    'sla.response.item3': 'دعم الدردشة: مباشر خلال ساعات العمل',
    'sla.changes.title': 'طلبات التغيير',
    'sla.changes.item1': 'باقة Starter: تغييران شهرياً',
    'sla.changes.item2': 'باقة Pro: تغييرات غير محدودة',
    'sla.changes.item3': 'معظم التغييرات تُنجز خلال 48 ساعة',
    'sla.scope.title': 'ما المشمول',
    'sla.scope.item1': 'استضافة وصيانة الموقع',
    'sla.scope.item2': 'تحديثات الأمان والنسخ الاحتياطي',
    'sla.scope.item3': 'تحديثات المحتوى (نصوص، صور، تخطيط)',
    'sla.scope.item4': 'الدعم الفني وحل المشاكل',
    'sla.limits.title': 'معلومات مهمة',
    'sla.limits.item1': 'إعادة التصميم الكبيرة قد تحتاج نقاش إضافي',
    'sla.limits.item2': 'الميزات المعقدة تحتاج باقة Pro',
    'sla.limits.item3': 'لا نخزن بيانات حساسة كالكلمات السرية',
    'sla.promise.title': 'وعدنا',
    'sla.promise.desc': 'نحن هنا لتسهيل حياتك. إذا لم يعمل شيء، سنصلحه. إذا كنت محتاراً، سنشرح. ستتحدث دائماً مع إنسان حقيقي يهتم بنجاحك.',
    
    // Services
    'services.title': 'أسعار بسيطة وصادقة',
    'services.subtitle': 'ابدأ مجاناً تماماً. قم بالترقية فقط إذا احتجت المزيد.',
    'services.starter.title': 'Starter',
    'services.starter.price': '$0.99',
    'services.starter.period': '/شهرياً',
    'services.starter.feature1': 'موقع جميل واحترافي',
    'services.starter.feature2': 'تغييران شهرياً',
    'services.starter.feature3': 'دعم بشري مشمول',
    'services.starter.feature4': 'الاستضافة مشمولة',
    'services.starter.feature5': 'الصيانة مشمولة',
    'services.starter.cta': 'ابدأ الآن',
    'services.pro.title': 'Pro',
    'services.pro.price': '$4.99',
    'services.pro.period': '/شهرياً',
    'services.pro.feature1': 'كل ما في Starter',
    'services.pro.feature2': 'تغييرات غير محدودة',
    'services.pro.feature3': 'دعم بشري أولوية',
    'services.pro.feature4': 'الاستضافة مشمولة',
    'services.pro.feature5': 'الصيانة مشمولة',
    'services.pro.cta': 'ترقية إلى Pro',
    'services.free.title': 'مجاني للأبد',
    'services.free.price': '$0',
    'services.free.period': '/شهرياً',
    'services.free.feature1': 'موقع جميل واحترافي',
    'services.free.feature2': 'استضافة مجانية — دائماً',
    'services.free.feature3': 'الأمان والتحديثات مشمولة',
    'services.free.feature4': 'مدير حساب خاص بك',
    'services.free.feature5': 'دعم ودود عبر البريد',
    'services.free.cta': 'ابدأ مجاناً',
    'services.concierge.title': 'الكونسيرج',
    'services.concierge.price': '$49',
    'services.concierge.period': '/شهرياً',
    'services.concierge.feature1': 'كل ما في المجاني',
    'services.concierge.feature2': 'تعديلات غير محدودة',
    'services.concierge.feature3': 'دعم أولوية عبر الهاتف والدردشة',
    'services.concierge.feature4': 'ميزات متقدمة عند الطلب',
    'services.concierge.feature5': 'تكاملات مخصصة',
    'services.concierge.cta': 'ترقية للكونسيرج',
    
    // Labs
    'labs.title': 'قريباً',
    'labs.subtitle': 'نحن نتحسن دائماً. إليك ما هو قادم.',
    'labs.ai.title': 'اقتراحات أذكى',
    'labs.ai.desc': 'سنساعدك بأفكار للتصميم ونصائح للمحتوى — مدعومة بتقنية ذكية، تُقدم بواسطة بشر.',
    'labs.deploy.title': 'أسرع وأكثر موثوقية',
    'labs.deploy.desc': 'موقعك سيُحمّل أسرع ويبقى متاحاً مهما حدث.',
    'labs.coming': 'قيد التطوير',
    
    // CTA
    'cta.title': 'مستعد للبدء؟',
    'cta.subtitle': 'تحدث مع شخص حقيقي اليوم. موقعك يمكن أن يكون جاهزاً هذا الأسبوع — ومجاناً.',
    'cta.button': 'لنتحدث — مجاناً',
    
    // Auth
    'auth.login.title': 'أهلاً بعودتك',
    'auth.login.subtitle': 'سجل دخولك لإدارة طلبات موقعك',
    'auth.login.button': 'تسجيل الدخول',
    'auth.signup.title': 'إنشاء حساب',
    'auth.signup.subtitle': 'انضم إلينا لبدء بناء موقعك',
    'auth.signup.button': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'كلمة المرور',
    'auth.passwordPlaceholder': '••••••••',
    'auth.loading': 'يرجى الانتظار...',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.signupLink': 'أنشئ واحداً',
    'auth.loginLink': 'سجل دخولك',
    'auth.success.login': 'أهلاً بعودتك!',
    'auth.success.loginDesc': 'تم تسجيل دخولك بنجاح.',
    'auth.success.signup': 'تم إنشاء الحساب!',
    'auth.success.signupDesc': 'مرحباً بك في أوريكا ويب. يمكنك الآن تقديم طلب موقعك.',
    'auth.error.title': 'حدث خطأ',
    'auth.error.alreadyRegistered': 'هذا البريد مسجل بالفعل. يرجى تسجيل الدخول.',
    
    // Dashboard
    'dashboard.loading': 'جاري التحميل...',
    'dashboard.welcome': 'لوحة التحكم',
    'dashboard.newRequest': 'طلب موقع جديد',
    'dashboard.logout': 'تسجيل الخروج',
    'dashboard.empty.title': 'لا توجد طلبات بعد',
    'dashboard.empty.desc': 'مستعد للحصول على موقعك الأول؟ انقر أدناه للبدء — يستغرق دقائق فقط.',
    'dashboard.empty.cta': 'إنشاء موقعي الأول',
    'dashboard.status.pending': 'قيد المراجعة',
    'dashboard.status.inProgress': 'قيد العمل',
    'dashboard.status.complete': 'مكتمل',
    
    // Request Form
    'request.step': 'الخطوة',
    'request.promise': 'جاهز في 24 ساعة',
    'request.yourIdea': 'فكرة موقعك',
    'request.step1.title': 'أخبرنا عن نفسك',
    'request.step2.title': 'عن موقعك',
    'request.step3.title': 'التفضيلات النهائية',
    'request.fullName': 'الاسم الكامل',
    'request.fullNamePlaceholder': 'أحمد محمد',
    'request.email': 'البريد الإلكتروني',
    'request.emailPlaceholder': 'your@email.com',
    'request.phone': 'رقم الهاتف',
    'request.phonePlaceholder': '+966 50 000 0000',
    'request.entityType': 'أنت...',
    'request.entity.individual': 'فرد',
    'request.entity.business': 'شركة',
    'request.entity.ngo': 'مؤسسة خيرية',
    'request.websiteGoal': 'ماذا يجب أن يفعل موقعك؟',
    'request.goal.showcase': 'عرض أعمالي',
    'request.goal.services': 'عرض خدماتي',
    'request.goal.contact': 'تسهيل التواصل',
    'request.goal.information': 'مشاركة معلومات',
    'request.preferredLanguage': 'لغة الموقع',
    'request.stylePreference': 'النمط المفضل',
    'request.style.modern': 'عصري ونظيف',
    'request.style.classic': 'كلاسيكي وأنيق',
    'request.style.minimal': 'بسيط ومختصر',
    'request.style.colorful': 'ملون ومرح',
    'request.consent': 'بتقديم هذا الطلب، أؤكد صحة معلوماتي وأوافق على دفع الرسوم المطلوبة بعد مراجعة واستلام موقعي.',
    'request.back': 'رجوع',
    'request.next': 'متابعة',
    'request.submit': 'إرسال الطلب',
    'request.submitting': 'جاري الإرسال...',
    'request.success.title': 'تم إرسال الطلب!',
    'request.success.desc': 'استلمنا طلبك. توقع النسخة الأولى من موقعك خلال 24 ساعة!',
    'request.error.title': 'حدث خطأ',
    
    // Plans - Mini Table
    'plans.badge': 'أسعار بسيطة',
    'plans.title': 'اختر خطتك',
    'plans.subtitle': 'من صفحات الهبوط المجانية إلى أنظمة الأعمال الكاملة. بدون رسوم خفية.',
    'plans.standard.name': 'قياسي',
    'plans.standard.highlight': 'تغيير واحد / شهرياً • نطاق فرعي مجاني',
    'plans.standard.cta': 'ابدأ مجاناً',
    'plans.standard.subtitle': 'مثالي للمبتدئين',
    'plans.pro.name': 'احترافي',
    'plans.pro.highlight': 'موقع متعدد الصفحات • تغييرات أسبوعية',
    'plans.pro.cta': 'انطلق الآن',
    'plans.pro.subtitle': 'للشركات النامية',
    'plans.pro.yearlySaving': 'وفر شهرين',
    'plans.business.name': 'أعمال',
    'plans.business.highlight': 'أنظمة كاملة • تغييرات غير محدودة',
    'plans.business.cta': 'اطلب عرضاً',
    'plans.business.subtitle': 'حلول متكاملة',
    'plans.business.yearlySaving': 'وفر $100',
    'plans.popular': 'الأكثر شيوعاً',
    'plans.free': 'مجاني',
    'plans.month': 'شهر',
    'plans.year': 'سنة',
    'plans.viewFull': 'عرض المقارنة الكاملة',
    'plans.pageTitle': 'الأسعار والخطط الكاملة',
    'plans.pageSubtitle': 'أسعار شفافة لكل مرحلة من مراحل عملك. ابدأ مجاناً، توسع عندما تكون مستعداً.',
    'plans.compareTitle': 'مقارنة الميزات الكاملة',
    'plans.table.feature': 'الميزة',
    'plans.table.hosting': 'الاستضافة والصيانة',
    'plans.table.hostingTip': 'نتولى كل الاستضافة والتحديثات الأمنية والنسخ الاحتياطي نيابة عنك.',
    'plans.table.domain': 'اسم النطاق',
    'plans.table.domainTip': 'عنوان موقعك (مثل: yourcompany.com).',
    'plans.table.domainSetup': 'إعداد النطاق',
    'plans.table.domainSetupTip': 'كيف نساعدك في إعداد نطاقك.',
    'plans.table.buildType': 'نوع البناء',
    'plans.table.buildTypeTip': 'تعقيد ونوع الموقع الذي نبنيه.',
    'plans.table.database': 'قاعدة البيانات / النظام',
    'plans.table.databaseTip': 'تخزين البيانات للمحتوى الديناميكي والمستخدمين والمنتجات.',
    'plans.table.delivery': 'وقت التسليم',
    'plans.table.deliveryTip': 'الوقت لاستلام أول نسخة جاهزة للإطلاق.',
    'plans.table.scaling': 'التوسع (التعديلات)',
    'plans.table.scalingTip': 'عدد المرات التي يمكنك طلب تغييرات على موقعك.',
    'plans.table.support': 'نوع الدعم',
    'plans.table.supportTip': 'كيف يمكنك الوصول إلينا للمساعدة.',
    'plans.table.response': 'وقت الاستجابة',
    'plans.table.responseTip': 'سرعة ردنا على طلباتك.',
    'plans.table.monthly': 'السعر الشهري',
    'plans.table.yearly': 'السعر السنوي',
    'plans.features.hostingFree': 'مجاني للأبد',
    'plans.features.hostingDb': 'مجاني + صيانة قاعدة البيانات',
    'plans.features.hostingFull': 'مجاني + صيانة النظام الكامل',
    'plans.features.subdomain': 'نطاق فرعي مجاني',
    'plans.features.customDomain': 'نطاق مخصص مجاني',
    'plans.features.domainConnect': 'اربط نطاقك الخاص',
    'plans.features.domainDone': 'إعداد جاهز لك',
    'plans.features.landingPage': 'صفحة هبوط سريعة',
    'plans.features.multiPage': 'موقع احترافي متعدد الصفحات',
    'plans.features.fullSystem': 'أنظمة كاملة معقدة',
    'plans.features.na': 'غير متاح',
    'plans.features.db5k': 'حتى 5,000 سجل / 1 جيجا',
    'plans.features.db50k': 'حتى 50,000 سجل / نطاق كامل',
    'plans.features.delivery48h': '48 ساعة للإطلاق',
    'plans.features.delivery5d': '48 ساعة عادي / 5 أيام معقد',
    'plans.features.scaling1': 'تغيير واحد / شهرياً',
    'plans.features.scalingWeek': 'تغيير واحد / أسبوعياً',
    'plans.features.scalingUnlimited': 'تغييرات غير محدودة',
    'plans.features.supportEmail': 'البريد والدردشة',
    'plans.features.supportVideo': 'البريد والدردشة واجتماعات الفيديو',
    'plans.features.supportDedicated': 'مدير مخصص + كل القنوات',
    'plans.features.response2d': 'يومان عمل',
    'plans.features.response1d': 'يوم عمل واحد',
    'plans.features.responseSameDay': 'نفس اليوم / أولوية',
    'addons.title': 'إضافات مميزة',
    'addons.subtitle': 'حسّن موقعك بخدمات احترافية.',
    'addons.seo': 'تعزيز SEO من أوريكا',
    'addons.copywriting': 'كتابة محتوى احترافية',
    'addons.speedAudit': 'تدقيق السرعة والأداء',
    'addons.branding': 'شعار وحزمة هوية',
    'addons.social': 'تكامل وسائل التواصل',
    'addons.analytics': 'إعداد التحليلات والتحويل',
    'addons.extraPage': 'صفحة / ميزة إضافية',
    'addons.prioritySupport': 'ترقية الدعم الأولوي',
    'addons.landingPage': 'صفحة تسويقية',
    'addons.perPage': '/صفحة',
    'addons.perSite': '/موقع',
    'addons.oneTime': 'مرة واحدة',
    'addons.freeProBusiness': 'مجاني في Pro/Business',
    'plans.antiDiy.title': 'توقف عن العناء مع أدوات السحب والإفلات',
    'plans.antiDiy.desc': 'في أوريكا ويب، نقدم دعماً محوره الإنسان. ترسل الطلب، نسلم النسخة الجاهزة للإطلاق في 48 ساعة. بدون متاعب، بدون منحنى تعلم، فقط نتائج.',
    'plans.antiDiy.delivery': 'تسليم 48 ساعة',
    'plans.antiDiy.support': 'دعم بشري',
    'plans.versionNote': 'جاهز للإنتاج وقابل للتوسع',
    'plans.cta.title': 'مستعد للبدء؟',
    'plans.cta.subtitle': 'أخبرنا عن مشروعك وسنتولى الباقي. النسخة الأولى في 48 ساعة.',
    'plans.cta.button': 'ابدأ موقعك الآن',
    
    // Footer
    'footer.tagline': 'مواقع بسيطة. دعم بشري.',
    'footer.services': 'الخدمات',
    'footer.company': 'الشركة',
    'footer.legal': 'قانوني',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    'footer.about': 'عنا',
    'footer.contact': 'تواصل',
    'footer.copyright': '© 2025 أوريكا سولوشنز. جميع الحقوق محفوظة.',
    'footer.ideal': 'مثالي للشركات الصغيرة والمؤسسات الخيرية وأي شخص يريد موقعاً رائعاً بدون تعقيد.',
  },
  de: {
    'nav.howItWorks': 'So funktioniert es',
    'nav.humanGuided': 'Unser Ansatz',
    'nav.services': 'Pakete',
    'nav.labs': 'Demnächst',
    'nav.login': 'Anmelden',
    'nav.getStarted': 'Kostenlos starten',
    'nav.theme': 'Design',
    'nav.sla': 'Servicevereinbarung',
    'hero.headline': 'Ihre Website.',
    'hero.headlineAccent': 'Unsere Expertise.',
    'hero.subheadline': 'Wir erstellen schöne, professionelle Websites für Menschen, die sich nicht mit Technik beschäftigen möchten. Sie sprechen mit einem echten Menschen. Wir kümmern uns um alles andere — komplett kostenlos starten.',
    'hero.cta.primary': 'Sprechen Sie mit uns — Kostenlos',
    'hero.cta.secondary': 'So funktioniert es',
    'hero.badge': 'Gemacht für Menschen, nicht für Techniker',
    'hero.input.placeholder': 'Beschreiben Sie Ihre Website-Idee in einem Satz...',
    'hero.input.submit': 'Weiter',
    'hero.input.examples': 'Beispiele',
    'hero.trust.noCard': 'Keine Kreditkarte erforderlich',
    'hero.trust.human': 'Echte menschliche Unterstützung',
    'hero.trust.free': 'Kostenlos starten',
    'example.clinic': 'Website für meine Praxis',
    'example.nonprofit': 'Website für eine gemeinnützige Organisation',
    'example.business': 'Landingpage für mein Unternehmen',
    'paths.back': 'Idee ändern',
    'paths.yourIdea': 'Ihre Idee',
    'paths.recommendation': 'Basierend auf Ihrer Idee empfehlen wir',
    'paths.recommended': 'Empfohlen',
    'paths.select': 'Diese Option wählen',
    'paths.promise': 'Erste Version innerhalb von 24 Stunden',
    'paths.chat.title': 'Mit einem Menschen sprechen',
    'paths.chat.desc': 'Chatten Sie jetzt mit einer echten Person. Wir helfen Ihnen herauszufinden, was Sie brauchen.',
    'paths.chat.badge': 'Sofort',
    'paths.meeting.title': 'Termin vereinbaren',
    'paths.meeting.desc': 'Buchen Sie einen Videoanruf innerhalb von 48 Stunden. Perfekt für detaillierte Gespräche.',
    'paths.meeting.badge': 'Innerhalb 48h',
    'paths.questions.title': 'Schnelle Fragen',
    'paths.questions.desc': 'Beantworten Sie ein paar einfache Fragen und wir fangen an. Der schnellste Weg zu Ihrer Website.',
    'paths.questions.badge': 'Fertig in 24h',
    'humanGuided.title': 'Sie müssen Technik nicht verstehen. Wir schon.',
    'humanGuided.subtitle': 'Ob kleines Unternehmen, gemeinnützige Organisation oder jemand mit einer Idee — wir sind hier, um zu helfen. Kein Fachjargon. Keine Verwirrung. Nur freundliche, menschliche Unterstützung.',
    'humanGuided.human.title': 'Immer menschlich',
    'humanGuided.human.desc': 'Sie sprechen nie mit einem Roboter. Ein echter Mensch begleitet Sie bei jedem Schritt.',
    'humanGuided.manager.title': 'Ihr Account Manager',
    'humanGuided.manager.desc': 'Jeder Kunde erhält einen persönlichen Ansprechpartner, der Ihr Projekt in- und auswendig kennt.',
    'humanGuided.worry.title': 'Keine Sorgen',
    'humanGuided.worry.desc': 'Wir kümmern uns um Hosting, Sicherheit, Updates und alles Technische. Sie konzentrieren sich auf Ihr Geschäft.',
    'humanGuided.support.title': 'Wir helfen gerne',
    'humanGuided.support.desc': 'Haben Sie eine Frage? Brauchen Sie eine Änderung? Fragen Sie einfach. Wir antworten schnell und freundlich.',
    'humanGuided.quote': 'Sie sprechen mit einem Menschen. Wir erledigen alles andere.',
    'howItWorks.title': 'So funktioniert es',
    'howItWorks.subtitle': 'Ihre Website zu bekommen ist einfach. Wir begleiten Sie durch jeden Schritt.',
    'howItWorks.step1.title': 'Erzählen Sie uns Ihre Idee',
    'howItWorks.step1.desc': 'Teilen Sie uns mit, was Sie brauchen — eine Website für Ihr Unternehmen, Ihre Organisation oder Ihr Projekt. Keine technischen Kenntnisse erforderlich.',
    'howItWorks.step2.title': 'Wir begleiten Sie',
    'howItWorks.step2.desc': 'Ihr Account Manager hilft Ihnen bei einfachen Entscheidungen zu Design und Inhalt. Wir erklären alles verständlich.',
    'howItWorks.step3.title': 'Wir bauen es für Sie',
    'howItWorks.step3.desc': 'Unser Team erstellt Ihre Website mit Sorgfalt. Sie genehmigen nur die Ergebnisse — keine Arbeit für Sie.',
    'howItWorks.step4.title': 'Laufende Unterstützung',
    'howItWorks.step4.desc': 'Ihre Website bleibt online, sicher und aktuell. Brauchen Sie Änderungen? Fragen Sie einfach Ihren Account Manager.',
    'hiw.title': 'So funktioniert es',
    'hiw.subtitle': 'Ihre Website zu bekommen ist einfach. Wir begleiten Sie durch jeden Schritt — keine technischen Kenntnisse nötig.',
    'hiw.promise': 'Erste Version innerhalb von 24 Stunden',
    'hiw.step1.title': 'Wählen Sie Ihre Domain',
    'hiw.step1.desc': 'Wählen Sie einen Namen für Ihre Website. Wir prüfen die Verfügbarkeit und übernehmen die Registrierung.',
    'hiw.step2.title': 'Beantworten Sie ein paar Fragen',
    'hiw.step2.desc': 'Erzählen Sie uns von Ihrem Unternehmen und was Ihre Website können soll. Nur einfache Fragen, nichts Technisches.',
    'hiw.step3.title': 'Wir bauen Ihre Website',
    'hiw.step3.desc': 'Unser Team erstellt eine schöne, professionelle Website basierend auf Ihren Antworten. Sie sehen sie innerhalb von 24 Stunden.',
    'hiw.step4.title': 'Prüfen & Online gehen',
    'hiw.step4.desc': 'Schauen Sie sich Ihre neue Website an und sagen Sie uns, wenn Sie Änderungen wünschen. Wenn Sie zufrieden sind, veröffentlichen wir sie.',
    'hiw.step5.title': 'Laufende menschliche Unterstützung',
    'hiw.step5.desc': 'Brauchen Sie Änderungen? Haben Sie Fragen? Ihr persönlicher Account Manager ist immer für Sie da.',
    'hiw.included.title': 'Was enthalten ist',
    'hiw.included.item1': 'Schönes, professionelles Website-Design',
    'hiw.included.item2': 'Kostenloses Hosting — für immer',
    'hiw.included.item3': 'Sicherheit und Updates inklusive',
    'hiw.included.item4': 'Ihr eigener Account Manager',
    'hiw.included.item5': 'Mobilfreundliches Design',
    'hiw.included.item6': 'Grundlegende SEO-Einrichtung',
    'hiw.cta.title': 'Bereit anzufangen?',
    'hiw.cta.subtitle': 'Beschreiben Sie Ihre Idee und wir begleiten Sie durch den Rest.',
    'hiw.cta.button': 'Jetzt starten — Kostenlos',
    'sla.title': 'Servicevereinbarung',
    'sla.subtitle': 'Klare, ehrliche Bedingungen. Wir möchten, dass Sie genau wissen, was Sie von uns erwarten können.',
    'sla.response.title': 'Reaktionszeiten',
    'sla.response.item1': 'E-Mail-Anfragen: Antwort innerhalb von 24 Stunden an Werktagen',
    'sla.response.item2': 'Dringende Probleme: Prioritätsantwort innerhalb von 4 Stunden',
    'sla.response.item3': 'Chat-Support: Echtzeit während der Geschäftszeiten',
    'sla.changes.title': 'Änderungsanfragen',
    'sla.changes.item1': 'Starter-Plan: 2 Änderungen pro Monat inklusive',
    'sla.changes.item2': 'Pro-Plan: Unbegrenzte Änderungen inklusive',
    'sla.changes.item3': 'Die meisten Änderungen werden innerhalb von 48 Stunden abgeschlossen',
    'sla.scope.title': 'Was abgedeckt ist',
    'sla.scope.item1': 'Website-Hosting und Wartung',
    'sla.scope.item2': 'Sicherheitsupdates und Backups',
    'sla.scope.item3': 'Inhaltsaktualisierungen (Text, Bilder, grundlegendes Layout)',
    'sla.scope.item4': 'Technischer Support und Fehlerbehebung',
    'sla.limits.title': 'Gut zu wissen',
    'sla.limits.item1': 'Größere Neugestaltungen erfordern möglicherweise zusätzliche Gespräche',
    'sla.limits.item2': 'Komplexe Funktionen (E-Commerce, Buchungssysteme) erfordern Pro-Plan',
    'sla.limits.item3': 'Wir speichern keine sensiblen Daten wie Passwörter oder Zahlungsinformationen',
    'sla.promise.title': 'Unser Versprechen',
    'sla.promise.desc': 'Wir sind hier, um Ihr Leben einfacher zu machen. Wenn etwas nicht funktioniert, reparieren wir es. Wenn Sie verwirrt sind, erklären wir es. Sie werden immer mit einem echten Menschen sprechen, dem Ihr Erfolg wichtig ist.',
    'services.title': 'Einfache, ehrliche Preise',
    'services.subtitle': 'Starten Sie komplett kostenlos. Upgraden Sie nur, wenn Sie mehr brauchen.',
    'services.starter.title': 'Starter',
    'services.starter.price': '0,99€',
    'services.starter.period': '/Monat',
    'services.starter.feature1': 'Schöne, professionelle Website',
    'services.starter.feature2': '2 Änderungen pro Monat',
    'services.starter.feature3': 'Menschlicher Support inklusive',
    'services.starter.feature4': 'Hosting inklusive',
    'services.starter.feature5': 'Wartung inklusive',
    'services.starter.cta': 'Jetzt starten',
    'services.pro.title': 'Pro',
    'services.pro.price': '4,99€',
    'services.pro.period': '/Monat',
    'services.pro.feature1': 'Alles aus Starter',
    'services.pro.feature2': 'Unbegrenzte Änderungen',
    'services.pro.feature3': 'Prioritäts-Support',
    'services.pro.feature4': 'Hosting inklusive',
    'services.pro.feature5': 'Wartung inklusive',
    'services.pro.cta': 'Upgrade zu Pro',
    'services.free.title': 'Für immer kostenlos',
    'services.free.price': '0€',
    'services.free.period': '/Monat',
    'services.free.feature1': 'Schöne, professionelle Website',
    'services.free.feature2': 'Kostenloses Hosting — immer',
    'services.free.feature3': 'Sicherheit und Updates inklusive',
    'services.free.feature4': 'Ihr eigener Account Manager',
    'services.free.feature5': 'Freundlicher E-Mail-Support',
    'services.free.cta': 'Kostenlos starten',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '49€',
    'services.concierge.period': '/Monat',
    'services.concierge.feature1': 'Alles aus Free',
    'services.concierge.feature2': 'Unbegrenzte Website-Änderungen',
    'services.concierge.feature3': 'Prioritäts-Support per Telefon & Chat',
    'services.concierge.feature4': 'Erweiterte Funktionen auf Anfrage',
    'services.concierge.feature5': 'Individuelle Integrationen',
    'services.concierge.cta': 'Upgrade zu Concierge',
    'labs.title': 'Demnächst',
    'labs.subtitle': 'Wir verbessern uns ständig. Das kommt als Nächstes.',
    'labs.ai.title': 'Intelligentere Vorschläge',
    'labs.ai.desc': 'Wir helfen Ihnen mit Design-Ideen und Inhaltstipps — unterstützt von intelligenter Technologie, geliefert von Menschen.',
    'labs.deploy.title': 'Schneller & Zuverlässiger',
    'labs.deploy.desc': 'Ihre Website wird noch schneller laden und immer online bleiben.',
    'labs.coming': 'In Entwicklung',
    'cta.title': 'Bereit anzufangen?',
    'cta.subtitle': 'Sprechen Sie heute mit einem echten Menschen. Ihre Website könnte diese Woche online sein — und sie ist kostenlos.',
    'cta.button': 'Lassen Sie uns reden — Kostenlos',
    'auth.login.title': 'Willkommen zurück',
    'auth.login.subtitle': 'Melden Sie sich an, um Ihre Website-Anfragen zu verwalten',
    'auth.login.button': 'Anmelden',
    'auth.signup.title': 'Konto erstellen',
    'auth.signup.subtitle': 'Treten Sie bei, um Ihre Website zu erstellen',
    'auth.signup.button': 'Konto erstellen',
    'auth.email': 'E-Mail',
    'auth.emailPlaceholder': 'ihre@email.de',
    'auth.password': 'Passwort',
    'auth.passwordPlaceholder': '••••••••',
    'auth.loading': 'Bitte warten...',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.signupLink': 'Erstellen Sie eines',
    'auth.loginLink': 'Anmelden',
    'auth.success.login': 'Willkommen zurück!',
    'auth.success.loginDesc': 'Sie haben sich erfolgreich angemeldet.',
    'auth.success.signup': 'Konto erstellt!',
    'auth.success.signupDesc': 'Willkommen bei Aureka Web. Sie können jetzt Ihre Website-Anfrage einreichen.',
    'auth.error.title': 'Etwas ist schiefgelaufen',
    'auth.error.alreadyRegistered': 'Diese E-Mail ist bereits registriert. Bitte melden Sie sich an.',
    'dashboard.loading': 'Lädt...',
    'dashboard.welcome': 'Ihr Dashboard',
    'dashboard.newRequest': 'Neue Website-Anfrage',
    'dashboard.logout': 'Abmelden',
    'dashboard.empty.title': 'Noch keine Website-Anfragen',
    'dashboard.empty.desc': 'Bereit für Ihre erste Website? Klicken Sie unten, um zu starten — es dauert nur wenige Minuten.',
    'dashboard.empty.cta': 'Meine erste Website erstellen',
    'dashboard.status.pending': 'Ausstehend',
    'dashboard.status.inProgress': 'In Bearbeitung',
    'dashboard.status.complete': 'Abgeschlossen',
    'request.step': 'Schritt',
    'request.promise': 'Fertig in 24 Stunden',
    'request.yourIdea': 'Ihre Website-Idee',
    'request.step1.title': 'Erzählen Sie uns von sich',
    'request.step2.title': 'Über Ihre Website',
    'request.step3.title': 'Letzte Präferenzen',
    'request.fullName': 'Vollständiger Name',
    'request.fullNamePlaceholder': 'Max Mustermann',
    'request.email': 'E-Mail-Adresse',
    'request.emailPlaceholder': 'ihre@email.de',
    'request.phone': 'Telefonnummer',
    'request.phonePlaceholder': '+49 123 456 7890',
    'request.entityType': 'Sie sind...',
    'request.entity.individual': 'Einzelperson',
    'request.entity.business': 'Unternehmen',
    'request.entity.ngo': 'Gemeinnützig',
    'request.websiteGoal': 'Was soll Ihre Website tun?',
    'request.goal.showcase': 'Meine Arbeit zeigen',
    'request.goal.services': 'Meine Dienste auflisten',
    'request.goal.contact': 'Kontakt ermöglichen',
    'request.goal.information': 'Informationen teilen',
    'request.preferredLanguage': 'Website-Sprache',
    'request.stylePreference': 'Bevorzugter Stil',
    'request.style.modern': 'Modern & Sauber',
    'request.style.classic': 'Klassisch & Elegant',
    'request.style.minimal': 'Minimal & Einfach',
    'request.style.colorful': 'Bunt & Fröhlich',
    'request.consent': 'Mit dem Absenden dieser Anfrage bestätige ich, dass meine Angaben korrekt sind und ich mich bereit erkläre, die erforderlichen Gebühren nach Erhalt meiner Website zu zahlen.',
    'request.back': 'Zurück',
    'request.next': 'Weiter',
    'request.submit': 'Anfrage absenden',
    'request.submitting': 'Wird gesendet...',
    'request.success.title': 'Anfrage gesendet!',
    'request.success.desc': 'Wir haben Ihre Anfrage erhalten. Erwarten Sie Ihre erste Website-Version innerhalb von 24 Stunden!',
    'request.error.title': 'Etwas ist schiefgelaufen',
    
    // Plans - Mini Table
    'plans.badge': 'Einfache Preise',
    'plans.title': 'Wählen Sie Ihren Plan',
    'plans.subtitle': 'Von kostenlosen Landingpages bis hin zu kompletten Geschäftssystemen. Keine versteckten Gebühren.',
    'plans.standard.name': 'Standard',
    'plans.standard.highlight': '1 Änderung / Monat • Kostenlose Subdomain',
    'plans.standard.cta': 'Kostenlos starten',
    'plans.standard.subtitle': 'Perfekt für den Anfang',
    'plans.pro.name': 'Pro',
    'plans.pro.highlight': 'Mehrseitige Website • Wöchentliche Änderungen',
    'plans.pro.cta': 'Jetzt starten',
    'plans.pro.subtitle': 'Für wachsende Unternehmen',
    'plans.pro.yearlySaving': '2 Monate sparen',
    'plans.business.name': 'Business',
    'plans.business.highlight': 'Volle Systeme • Unbegrenzte Änderungen',
    'plans.business.cta': 'Demo anfordern',
    'plans.business.subtitle': 'Komplettlösungen',
    'plans.business.yearlySaving': '100€ sparen',
    'plans.popular': 'Am beliebtesten',
    'plans.free': 'Kostenlos',
    'plans.month': 'Mo',
    'plans.year': 'Jahr',
    'plans.viewFull': 'Vollständigen Vergleich anzeigen',
    'plans.pageTitle': 'Komplette Preise & Pläne',
    'plans.pageSubtitle': 'Transparente Preise für jede Phase Ihres Unternehmens. Kostenlos starten, skalieren wenn bereit.',
    'plans.compareTitle': 'Vollständiger Funktionsvergleich',
    'plans.table.feature': 'Funktion',
    'plans.table.hosting': 'Hosting & Wartung',
    'plans.table.hostingTip': 'Wir kümmern uns um Hosting, Sicherheitsupdates und Backups.',
    'plans.table.domain': 'Domain-Name',
    'plans.table.domainTip': 'Ihre Website-Adresse (z.B. ihrfirma.de).',
    'plans.table.domainSetup': 'Domain-Einrichtung',
    'plans.table.domainSetupTip': 'Wie wir Ihnen bei der Domain-Einrichtung helfen.',
    'plans.table.buildType': 'Bautyp',
    'plans.table.buildTypeTip': 'Komplexität und Art der Website, die wir erstellen.',
    'plans.table.database': 'Datenbank / System',
    'plans.table.databaseTip': 'Datenspeicher für dynamische Inhalte, Benutzer, Produkte.',
    'plans.table.delivery': 'Lieferzeit',
    'plans.table.deliveryTip': 'Zeit bis zur ersten startbereiten Version.',
    'plans.table.scaling': 'Skalierung (Änderungen)',
    'plans.table.scalingTip': 'Wie oft Sie Änderungen an Ihrer Website anfordern können.',
    'plans.table.support': 'Support-Art',
    'plans.table.supportTip': 'Wie Sie uns für Hilfe erreichen können.',
    'plans.table.response': 'Antwortzeit',
    'plans.table.responseTip': 'Wie schnell wir auf Ihre Anfragen antworten.',
    'plans.table.monthly': 'Monatlicher Preis',
    'plans.table.yearly': 'Jährlicher Preis',
    'plans.features.hostingFree': 'Für immer kostenlos',
    'plans.features.hostingDb': 'Kostenlos + Datenbankwartung',
    'plans.features.hostingFull': 'Kostenlos + Vollständige Systemwartung',
    'plans.features.subdomain': 'Kostenlose Subdomain',
    'plans.features.customDomain': 'Kostenlose eigene Domain',
    'plans.features.domainConnect': 'Eigene Domain verbinden',
    'plans.features.domainDone': 'Für Sie erledigt',
    'plans.features.landingPage': 'Schnelle Landingpage',
    'plans.features.multiPage': 'Professionelle mehrseitige Website',
    'plans.features.fullSystem': 'Komplexe volle Systeme',
    'plans.features.na': 'N/V',
    'plans.features.db5k': 'Bis 5.000 Einträge / 1 GB',
    'plans.features.db50k': 'Bis 50.000 Einträge / Volle Skala',
    'plans.features.delivery48h': '48 Stunden bis Start',
    'plans.features.delivery5d': '48h Standard / 5 Tage komplex',
    'plans.features.scaling1': '1 Änderung / Monat',
    'plans.features.scalingWeek': '1 Änderung / Woche',
    'plans.features.scalingUnlimited': 'Unbegrenzte Änderungen',
    'plans.features.supportEmail': 'E-Mail & Chat',
    'plans.features.supportVideo': 'E-Mail, Chat & Videomeetings',
    'plans.features.supportDedicated': 'Persönlicher Manager + Alle Kanäle',
    'plans.features.response2d': '2 Werktage',
    'plans.features.response1d': '1 Werktag',
    'plans.features.responseSameDay': 'Gleicher Tag / Priorität',
    'addons.title': 'Premium Add-ons',
    'addons.subtitle': 'Verbessern Sie Ihre Website mit professionellen Diensten.',
    'addons.seo': 'AUREKA SEO Boost',
    'addons.copywriting': 'Professionelles Copywriting',
    'addons.speedAudit': 'Speed & Performance Audit',
    'addons.branding': 'Logo & Branding Kit',
    'addons.social': 'Social Media Integration',
    'addons.analytics': 'Analytics & Conversion Setup',
    'addons.extraPage': 'Zusätzliche Seite / Feature',
    'addons.prioritySupport': 'Priority Support Upgrade',
    'addons.landingPage': 'Marketing Landingpage',
    'addons.perPage': '/Seite',
    'addons.perSite': '/Website',
    'addons.oneTime': 'einmalig',
    'addons.freeProBusiness': 'Kostenlos in Pro/Business',
    'plans.antiDiy.title': 'Schluss mit Drag-and-Drop-Buildern',
    'plans.antiDiy.desc': 'Bei AUREKA WEB bieten wir menschenzentrierten Support. Sie senden die Anfrage, wir liefern die startbereite Version in 48 Stunden. Kein Ärger, keine Lernkurve, nur Ergebnisse.',
    'plans.antiDiy.delivery': '48h Lieferung',
    'plans.antiDiy.support': 'Menschlicher Support',
    'plans.versionNote': 'Produktionsbereit & skalierbar',
    'plans.cta.title': 'Bereit anzufangen?',
    'plans.cta.subtitle': 'Erzählen Sie uns von Ihrem Projekt und wir kümmern uns um den Rest. Erste Version in 48 Stunden.',
    'plans.cta.button': 'Jetzt Website starten',
    
    'footer.tagline': 'Websites einfach gemacht. Support menschlich.',
    'footer.services': 'Dienste',
    'footer.company': 'Unternehmen',
    'footer.legal': 'Rechtliches',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'AGB',
    'footer.about': 'Über uns',
    'footer.contact': 'Kontakt',
    'footer.copyright': '© 2025 Aureka Solutions. Alle Rechte vorbehalten.',
    'footer.ideal': 'Perfekt für kleine Unternehmen, gemeinnützige Organisationen und alle, die eine tolle Website ohne Aufwand möchten.',
  },
  fr: {
    'nav.howItWorks': 'Comment ça marche',
    'nav.humanGuided': 'Notre approche',
    'nav.services': 'Forfaits',
    'nav.labs': 'Bientôt',
    'nav.login': 'Connexion',
    'nav.getStarted': 'Commencer gratuitement',
    'nav.theme': 'Thème',
    'nav.sla': 'Accord de service',
    'hero.headline': 'Votre site web.',
    'hero.headlineAccent': 'Notre expertise.',
    'hero.subheadline': 'Nous créons de beaux sites professionnels pour les personnes qui ne veulent pas s\'occuper de la technologie. Vous parlez à une vraie personne. Nous gérons tout le reste — entièrement gratuit pour commencer.',
    'hero.cta.primary': 'Parlons-en — C\'est gratuit',
    'hero.cta.secondary': 'Comment ça marche',
    'hero.badge': 'Fait pour les gens, pas pour les techniciens',
    'hero.input.placeholder': 'Décrivez votre idée de site en une phrase...',
    'hero.input.submit': 'Continuer',
    'hero.input.examples': 'Exemples',
    'hero.trust.noCard': 'Pas de carte bancaire requise',
    'hero.trust.human': 'Support humain réel',
    'hero.trust.free': 'Commencer gratuitement',
    'example.clinic': 'Site web pour ma clinique',
    'example.nonprofit': 'Site web pour une association',
    'example.business': 'Page d\'atterrissage pour mon entreprise',
    'paths.back': 'Changer mon idée',
    'paths.yourIdea': 'Votre idée',
    'paths.recommendation': 'Selon votre idée, nous recommandons',
    'paths.recommended': 'Recommandé',
    'paths.select': 'Choisir cette option',
    'paths.promise': 'Première version livrée sous 24 heures',
    'paths.chat.title': 'Parler à un humain',
    'paths.chat.desc': 'Chattez avec une vraie personne maintenant. Nous vous aiderons à définir vos besoins.',
    'paths.chat.badge': 'Immédiat',
    'paths.meeting.title': 'Planifier une réunion',
    'paths.meeting.desc': 'Réservez un appel vidéo sous 48 heures. Parfait pour des discussions détaillées.',
    'paths.meeting.badge': 'Sous 48h',
    'paths.questions.title': 'Questions rapides',
    'paths.questions.desc': 'Répondez à quelques questions simples et nous commençons. Le moyen le plus rapide d\'obtenir votre site.',
    'paths.questions.badge': 'Prêt en 24h',
    'humanGuided.title': 'Vous n\'avez pas besoin de comprendre la technologie. Nous, si.',
    'humanGuided.subtitle': 'Que vous soyez une petite entreprise, une association ou simplement quelqu\'un avec une idée — nous sommes là pour vous aider. Pas de jargon. Pas de confusion. Juste un support humain et amical.',
    'humanGuided.human.title': 'Toujours humain',
    'humanGuided.human.desc': 'Vous ne parlerez jamais à un robot. Une vraie personne vous guide à chaque étape.',
    'humanGuided.manager.title': 'Votre gestionnaire de compte',
    'humanGuided.manager.desc': 'Chaque client a un contact dédié qui connaît votre projet sur le bout des doigts.',
    'humanGuided.worry.title': 'Zéro souci',
    'humanGuided.worry.desc': 'Nous gérons l\'hébergement, la sécurité, les mises à jour et tout le technique. Vous vous concentrez sur votre activité.',
    'humanGuided.support.title': 'Nous sommes là pour aider',
    'humanGuided.support.desc': 'Une question ? Besoin d\'un changement ? Demandez simplement. Nous répondons rapidement et gentiment.',
    'humanGuided.quote': 'Vous parlez à un humain. Nous gérons tout le reste.',
    'howItWorks.title': 'Comment ça marche',
    'howItWorks.subtitle': 'Obtenir votre site web est simple. Nous vous guidons à chaque étape.',
    'howItWorks.step1.title': 'Parlez-nous de votre idée',
    'howItWorks.step1.desc': 'Dites-nous ce dont vous avez besoin — un site pour votre entreprise, association ou projet. Aucune connaissance technique requise.',
    'howItWorks.step2.title': 'Nous vous guidons',
    'howItWorks.step2.desc': 'Votre gestionnaire de compte vous aide à faire des choix simples de design et de contenu. Nous expliquons tout clairement.',
    'howItWorks.step3.title': 'Nous le construisons pour vous',
    'howItWorks.step3.desc': 'Notre équipe crée votre site avec soin. Vous approuvez simplement les résultats — aucun travail de votre côté.',
    'howItWorks.step4.title': 'Support continu',
    'howItWorks.step4.desc': 'Votre site reste en ligne, sécurisé et à jour. Besoin de changements ? Demandez à votre gestionnaire de compte.',
    'hiw.title': 'Comment ça marche',
    'hiw.subtitle': 'Obtenir votre site est simple. Nous vous guidons à chaque étape — aucune connaissance technique nécessaire.',
    'hiw.promise': 'Première version livrée sous 24 heures',
    'hiw.step1.title': 'Choisissez votre domaine',
    'hiw.step1.desc': 'Choisissez un nom pour votre site. Nous vérifierons sa disponibilité et gérerons l\'enregistrement pour vous.',
    'hiw.step2.title': 'Répondez à quelques questions',
    'hiw.step2.desc': 'Parlez-nous de votre activité et de ce que vous voulez que votre site fasse. Juste des questions simples, rien de technique.',
    'hiw.step3.title': 'Nous créons votre site',
    'hiw.step3.desc': 'Notre équipe crée un beau site professionnel basé sur vos réponses. Vous le verrez sous 24 heures.',
    'hiw.step4.title': 'Vérifier et mettre en ligne',
    'hiw.step4.desc': 'Découvrez votre nouveau site et dites-nous si vous souhaitez des modifications. Une fois satisfait, nous le publions.',
    'hiw.step5.title': 'Support humain continu',
    'hiw.step5.desc': 'Besoin de modifications ? Des questions ? Votre gestionnaire de compte dédié est toujours là pour vous aider.',
    'hiw.included.title': 'Ce qui est inclus',
    'hiw.included.item1': 'Design de site web beau et professionnel',
    'hiw.included.item2': 'Hébergement gratuit — pour toujours',
    'hiw.included.item3': 'Sécurité et mises à jour incluses',
    'hiw.included.item4': 'Votre propre gestionnaire de compte',
    'hiw.included.item5': 'Design adapté mobile',
    'hiw.included.item6': 'Configuration SEO de base',
    'hiw.cta.title': 'Prêt à commencer ?',
    'hiw.cta.subtitle': 'Décrivez votre idée et nous vous guiderons pour le reste.',
    'hiw.cta.button': 'Commencer maintenant — C\'est gratuit',
    'sla.title': 'Accord de service',
    'sla.subtitle': 'Des conditions claires et honnêtes. Nous voulons que vous sachiez exactement à quoi vous attendre.',
    'sla.response.title': 'Délais de réponse',
    'sla.response.item1': 'Demandes par email : Réponse sous 24 heures les jours ouvrables',
    'sla.response.item2': 'Problèmes urgents : Réponse prioritaire sous 4 heures',
    'sla.response.item3': 'Support chat : En temps réel pendant les heures de bureau',
    'sla.changes.title': 'Demandes de modification',
    'sla.changes.item1': 'Plan Starter : 2 modifications par mois incluses',
    'sla.changes.item2': 'Plan Pro : Modifications illimitées incluses',
    'sla.changes.item3': 'La plupart des modifications sont effectuées sous 48 heures',
    'sla.scope.title': 'Ce qui est couvert',
    'sla.scope.item1': 'Hébergement et maintenance du site',
    'sla.scope.item2': 'Mises à jour de sécurité et sauvegardes',
    'sla.scope.item3': 'Mises à jour de contenu (texte, images, mise en page)',
    'sla.scope.item4': 'Support technique et dépannage',
    'sla.limits.title': 'Bon à savoir',
    'sla.limits.item1': 'Les redesigns majeurs peuvent nécessiter une discussion supplémentaire',
    'sla.limits.item2': 'Les fonctionnalités complexes (e-commerce, réservation) nécessitent le plan Pro',
    'sla.limits.item3': 'Nous ne stockons pas de données sensibles comme les mots de passe',
    'sla.promise.title': 'Notre promesse',
    'sla.promise.desc': 'Nous sommes là pour vous simplifier la vie. Si quelque chose ne fonctionne pas, nous le réparons. Si vous êtes confus, nous expliquons. Vous parlerez toujours à un vrai humain qui se soucie de votre succès.',
    'services.title': 'Tarifs simples et honnêtes',
    'services.subtitle': 'Commencez entièrement gratuitement. Passez à la version supérieure seulement si vous en avez besoin.',
    'services.starter.title': 'Starter',
    'services.starter.price': '0,99€',
    'services.starter.period': '/mois',
    'services.starter.feature1': 'Site web beau et professionnel',
    'services.starter.feature2': '2 modifications par mois',
    'services.starter.feature3': 'Support humain inclus',
    'services.starter.feature4': 'Hébergement inclus',
    'services.starter.feature5': 'Maintenance incluse',
    'services.starter.cta': 'Commencer',
    'services.pro.title': 'Pro',
    'services.pro.price': '4,99€',
    'services.pro.period': '/mois',
    'services.pro.feature1': 'Tout de Starter',
    'services.pro.feature2': 'Modifications illimitées',
    'services.pro.feature3': 'Support prioritaire',
    'services.pro.feature4': 'Hébergement inclus',
    'services.pro.feature5': 'Maintenance incluse',
    'services.pro.cta': 'Passer à Pro',
    'services.free.title': 'Gratuit pour toujours',
    'services.free.price': '0€',
    'services.free.period': '/mois',
    'services.free.feature1': 'Site web beau et professionnel',
    'services.free.feature2': 'Hébergement gratuit — toujours',
    'services.free.feature3': 'Sécurité et mises à jour incluses',
    'services.free.feature4': 'Votre propre gestionnaire de compte',
    'services.free.feature5': 'Support email amical',
    'services.free.cta': 'Commencer gratuitement',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '49€',
    'services.concierge.period': '/mois',
    'services.concierge.feature1': 'Tout de Gratuit',
    'services.concierge.feature2': 'Modifications illimitées',
    'services.concierge.feature3': 'Support prioritaire téléphone & chat',
    'services.concierge.feature4': 'Fonctionnalités avancées sur demande',
    'services.concierge.feature5': 'Intégrations personnalisées',
    'services.concierge.cta': 'Passer à Concierge',
    'labs.title': 'Bientôt',
    'labs.subtitle': 'Nous nous améliorons constamment. Voici la suite.',
    'labs.ai.title': 'Suggestions plus intelligentes',
    'labs.ai.desc': 'Nous vous aiderons avec des idées de design et des conseils de contenu — propulsés par une technologie intelligente, livrés par des humains.',
    'labs.deploy.title': 'Plus rapide et plus fiable',
    'labs.deploy.desc': 'Votre site se chargera encore plus vite et restera en ligne quoi qu\'il arrive.',
    'labs.coming': 'En développement',
    'cta.title': 'Prêt à commencer ?',
    'cta.subtitle': 'Parlez à une vraie personne aujourd\'hui. Votre site pourrait être en ligne cette semaine — et c\'est gratuit.',
    'cta.button': 'Parlons-en — C\'est gratuit',
    'auth.login.title': 'Bon retour',
    'auth.login.subtitle': 'Connectez-vous pour gérer vos demandes de site',
    'auth.login.button': 'Se connecter',
    'auth.signup.title': 'Créer un compte',
    'auth.signup.subtitle': 'Rejoignez-nous pour créer votre site',
    'auth.signup.button': 'Créer un compte',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'votre@email.fr',
    'auth.password': 'Mot de passe',
    'auth.passwordPlaceholder': '••••••••',
    'auth.loading': 'Veuillez patienter...',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.signupLink': 'Créez-en un',
    'auth.loginLink': 'Se connecter',
    'auth.success.login': 'Bon retour !',
    'auth.success.loginDesc': 'Vous êtes connecté avec succès.',
    'auth.success.signup': 'Compte créé !',
    'auth.success.signupDesc': 'Bienvenue chez Aureka Web. Vous pouvez maintenant soumettre votre demande.',
    'auth.error.title': 'Quelque chose s\'est mal passé',
    'auth.error.alreadyRegistered': 'Cet email est déjà enregistré. Veuillez vous connecter.',
    'dashboard.loading': 'Chargement...',
    'dashboard.welcome': 'Votre tableau de bord',
    'dashboard.newRequest': 'Nouvelle demande de site',
    'dashboard.logout': 'Se déconnecter',
    'dashboard.empty.title': 'Pas encore de demandes',
    'dashboard.empty.desc': 'Prêt pour votre premier site ? Cliquez ci-dessous pour commencer — ça ne prend que quelques minutes.',
    'dashboard.empty.cta': 'Créer mon premier site',
    'dashboard.status.pending': 'En attente',
    'dashboard.status.inProgress': 'En cours',
    'dashboard.status.complete': 'Terminé',
    'request.step': 'Étape',
    'request.promise': 'Prêt en 24 heures',
    'request.yourIdea': 'Votre idée de site',
    'request.step1.title': 'Parlez-nous de vous',
    'request.step2.title': 'À propos de votre site',
    'request.step3.title': 'Préférences finales',
    'request.fullName': 'Nom complet',
    'request.fullNamePlaceholder': 'Jean Dupont',
    'request.email': 'Adresse email',
    'request.emailPlaceholder': 'votre@email.fr',
    'request.phone': 'Numéro de téléphone',
    'request.phonePlaceholder': '+33 1 23 45 67 89',
    'request.entityType': 'Vous êtes...',
    'request.entity.individual': 'Particulier',
    'request.entity.business': 'Entreprise',
    'request.entity.ngo': 'Association',
    'request.websiteGoal': 'Que doit faire votre site ?',
    'request.goal.showcase': 'Montrer mon travail',
    'request.goal.services': 'Lister mes services',
    'request.goal.contact': 'Permettre de me contacter',
    'request.goal.information': 'Partager des informations',
    'request.preferredLanguage': 'Langue du site',
    'request.stylePreference': 'Style préféré',
    'request.style.modern': 'Moderne & Épuré',
    'request.style.classic': 'Classique & Élégant',
    'request.style.minimal': 'Minimal & Simple',
    'request.style.colorful': 'Coloré & Amusant',
    'request.consent': 'En soumettant cette demande, je confirme que mes informations sont exactes et j\'accepte de payer les frais requis après avoir reçu mon site.',
    'request.back': 'Retour',
    'request.next': 'Continuer',
    'request.submit': 'Envoyer la demande',
    'request.submitting': 'Envoi en cours...',
    'request.success.title': 'Demande envoyée !',
    'request.success.desc': 'Nous avons reçu votre demande. Attendez-vous à votre première version sous 24 heures !',
    'request.error.title': 'Quelque chose s\'est mal passé',
    
    // Plans - Mini Table
    'plans.badge': 'Tarifs Simples',
    'plans.title': 'Choisissez Votre Plan',
    'plans.subtitle': 'Des pages d\'atterrissage gratuites aux systèmes d\'entreprise complets. Sans frais cachés.',
    'plans.standard.name': 'Standard',
    'plans.standard.highlight': '1 Modification / Mois • Sous-domaine Gratuit',
    'plans.standard.cta': 'Commencer Gratuitement',
    'plans.standard.subtitle': 'Parfait pour débuter',
    'plans.pro.name': 'Pro',
    'plans.pro.highlight': 'Site Multi-pages • Modifications Hebdomadaires',
    'plans.pro.cta': 'Lancer Maintenant',
    'plans.pro.subtitle': 'Pour les entreprises en croissance',
    'plans.pro.yearlySaving': 'Économisez 2 Mois',
    'plans.business.name': 'Business',
    'plans.business.highlight': 'Systèmes Complets • Modifications Illimitées',
    'plans.business.cta': 'Demander une Démo',
    'plans.business.subtitle': 'Solutions complètes',
    'plans.business.yearlySaving': 'Économisez 100€',
    'plans.popular': 'Le Plus Populaire',
    'plans.free': 'Gratuit',
    'plans.month': 'mois',
    'plans.year': 'an',
    'plans.viewFull': 'Voir la Comparaison Complète',
    'plans.pageTitle': 'Tarifs & Plans Complets',
    'plans.pageSubtitle': 'Tarification transparente pour chaque étape de votre entreprise. Commencez gratuitement, évoluez quand vous êtes prêt.',
    'plans.compareTitle': 'Comparaison Complète des Fonctionnalités',
    'plans.table.feature': 'Fonctionnalité',
    'plans.table.hosting': 'Hébergement & Maintenance',
    'plans.table.hostingTip': 'Nous gérons l\'hébergement, les mises à jour de sécurité et les sauvegardes.',
    'plans.table.domain': 'Nom de Domaine',
    'plans.table.domainTip': 'L\'adresse de votre site (ex: votreentreprise.fr).',
    'plans.table.domainSetup': 'Configuration du Domaine',
    'plans.table.domainSetupTip': 'Comment nous vous aidons à configurer votre domaine.',
    'plans.table.buildType': 'Type de Construction',
    'plans.table.buildTypeTip': 'Complexité et type de site que nous créons.',
    'plans.table.database': 'Base de Données / Système',
    'plans.table.databaseTip': 'Stockage pour le contenu dynamique, utilisateurs, produits.',
    'plans.table.delivery': 'Délai de Livraison',
    'plans.table.deliveryTip': 'Temps pour recevoir votre première version prête au lancement.',
    'plans.table.scaling': 'Évolution (Modifications)',
    'plans.table.scalingTip': 'Fréquence des modifications que vous pouvez demander.',
    'plans.table.support': 'Type de Support',
    'plans.table.supportTip': 'Comment nous contacter pour obtenir de l\'aide.',
    'plans.table.response': 'Temps de Réponse',
    'plans.table.responseTip': 'Rapidité de notre réponse à vos demandes.',
    'plans.table.monthly': 'Prix Mensuel',
    'plans.table.yearly': 'Prix Annuel',
    'plans.features.hostingFree': 'Gratuit Pour Toujours',
    'plans.features.hostingDb': 'Gratuit + Maintenance Base de Données',
    'plans.features.hostingFull': 'Gratuit + Maintenance Système Complète',
    'plans.features.subdomain': 'Sous-domaine Gratuit',
    'plans.features.customDomain': 'Domaine Personnalisé Gratuit',
    'plans.features.domainConnect': 'Connectez votre propre domaine',
    'plans.features.domainDone': 'Configuration clé en main',
    'plans.features.landingPage': 'Page d\'Atterrissage Rapide',
    'plans.features.multiPage': 'Site Multi-pages Professionnel',
    'plans.features.fullSystem': 'Systèmes Complets Complexes',
    'plans.features.na': 'N/A',
    'plans.features.db5k': 'Jusqu\'à 5 000 entrées / 1 Go',
    'plans.features.db50k': 'Jusqu\'à 50 000 entrées / Pleine Échelle',
    'plans.features.delivery48h': '48h pour le Lancement',
    'plans.features.delivery5d': '48h standard / 5 jours complexe',
    'plans.features.scaling1': '1 Modification / Mois',
    'plans.features.scalingWeek': '1 Modification / Semaine',
    'plans.features.scalingUnlimited': 'Modifications Illimitées',
    'plans.features.supportEmail': 'Email & Chat',
    'plans.features.supportVideo': 'Email, Chat & Réunions Vidéo',
    'plans.features.supportDedicated': 'Manager Dédié + Tous Canaux',
    'plans.features.response2d': '2 Jours Ouvrables',
    'plans.features.response1d': '1 Jour Ouvrable',
    'plans.features.responseSameDay': 'Même Jour / Priorité',
    'addons.title': 'Add-ons Premium',
    'addons.subtitle': 'Améliorez votre site avec des services professionnels.',
    'addons.seo': 'AUREKA SEO Boost',
    'addons.copywriting': 'Rédaction Professionnelle',
    'addons.speedAudit': 'Audit Vitesse & Performance',
    'addons.branding': 'Logo & Kit de Marque',
    'addons.social': 'Intégration Réseaux Sociaux',
    'addons.analytics': 'Configuration Analytics & Conversion',
    'addons.extraPage': 'Page / Fonctionnalité Supplémentaire',
    'addons.prioritySupport': 'Upgrade Support Prioritaire',
    'addons.landingPage': 'Page d\'Atterrissage Marketing',
    'addons.perPage': '/page',
    'addons.perSite': '/site',
    'addons.oneTime': 'unique',
    'addons.freeProBusiness': 'Gratuit dans Pro/Business',
    'plans.antiDiy.title': 'Arrêtez de Lutter avec les Builders Drag-and-Drop',
    'plans.antiDiy.desc': 'Chez AUREKA WEB, nous offrons un Support Centré sur l\'Humain. Vous envoyez la demande, nous livrons la Version Prête au Lancement en 48 heures. Sans tracas, sans courbe d\'apprentissage, juste des résultats.',
    'plans.antiDiy.delivery': 'Livraison 48h',
    'plans.antiDiy.support': 'Support Humain',
    'plans.versionNote': 'Prêt pour la production & évolutif',
    'plans.cta.title': 'Prêt à Commencer ?',
    'plans.cta.subtitle': 'Parlez-nous de votre projet et nous gérons le reste. Première version en 48 heures.',
    'plans.cta.button': 'Lancez Votre Site Maintenant',
    
    'footer.tagline': 'Sites web simplifiés. Support humain.',
    'footer.services': 'Services',
    'footer.company': 'Entreprise',
    'footer.legal': 'Légal',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2025 Aureka Solutions. Tous droits réservés.',
    'footer.ideal': 'Parfait pour les petites entreprises, les associations et tous ceux qui veulent un super site sans tracas.',
  },
  es: {
    'nav.howItWorks': 'Cómo funciona',
    'nav.humanGuided': 'Nuestro enfoque',
    'nav.services': 'Planes',
    'nav.labs': 'Próximamente',
    'nav.login': 'Iniciar sesión',
    'nav.getStarted': 'Empezar gratis',
    'nav.theme': 'Tema',
    'nav.sla': 'Acuerdo de servicio',
    'hero.headline': 'Tu sitio web.',
    'hero.headlineAccent': 'Nuestra experiencia.',
    'hero.subheadline': 'Creamos sitios web hermosos y profesionales para personas que no quieren lidiar con la tecnología. Hablas con una persona real. Nosotros nos encargamos de todo lo demás — completamente gratis para empezar.',
    'hero.cta.primary': 'Hablemos — Es gratis',
    'hero.cta.secondary': 'Cómo funciona',
    'hero.badge': 'Hecho para personas, no para técnicos',
    'hero.input.placeholder': 'Describe tu idea de sitio web en una oración...',
    'hero.input.submit': 'Continuar',
    'hero.input.examples': 'Ejemplos',
    'hero.trust.noCard': 'Sin tarjeta de crédito',
    'hero.trust.human': 'Soporte humano real',
    'hero.trust.free': 'Empezar gratis',
    'example.clinic': 'Sitio web para mi clínica',
    'example.nonprofit': 'Sitio web para una ONG',
    'example.business': 'Página de aterrizaje para mi negocio',
    'paths.back': 'Cambiar mi idea',
    'paths.yourIdea': 'Tu idea',
    'paths.recommendation': 'Según tu idea, recomendamos',
    'paths.recommended': 'Recomendado',
    'paths.select': 'Elegir esta opción',
    'paths.promise': 'Primera versión entregada en 24 horas',
    'paths.chat.title': 'Hablar con un humano',
    'paths.chat.desc': 'Chatea con una persona real ahora. Te ayudaremos a definir lo que necesitas.',
    'paths.chat.badge': 'Inmediato',
    'paths.meeting.title': 'Programar una reunión',
    'paths.meeting.desc': 'Reserva una videollamada en 48 horas. Perfecto para conversaciones detalladas.',
    'paths.meeting.badge': 'En 48h',
    'paths.questions.title': 'Preguntas rápidas',
    'paths.questions.desc': 'Responde algunas preguntas simples y empezamos. La forma más rápida de obtener tu sitio.',
    'paths.questions.badge': 'Listo en 24h',
    'humanGuided.title': 'No necesitas entender la tecnología. Nosotros sí.',
    'humanGuided.subtitle': 'Ya seas un pequeño negocio, una ONG o simplemente alguien con una idea — estamos aquí para ayudar. Sin jerga. Sin confusión. Solo apoyo humano y amigable.',
    'humanGuided.human.title': 'Siempre humano',
    'humanGuided.human.desc': 'Nunca hablarás con un robot. Una persona real te guía en cada paso.',
    'humanGuided.manager.title': 'Tu gestor de cuenta',
    'humanGuided.manager.desc': 'Cada cliente tiene un contacto dedicado que conoce tu proyecto al dedillo.',
    'humanGuided.worry.title': 'Cero preocupaciones',
    'humanGuided.worry.desc': 'Nos encargamos del hosting, seguridad, actualizaciones y todo lo técnico. Tú te enfocas en tu negocio.',
    'humanGuided.support.title': 'Estamos para ayudar',
    'humanGuided.support.desc': '¿Tienes una pregunta? ¿Necesitas un cambio? Solo pregunta. Respondemos rápido y con amabilidad.',
    'humanGuided.quote': 'Hablas con un humano. Nosotros nos encargamos de todo lo demás.',
    'howItWorks.title': 'Cómo funciona',
    'howItWorks.subtitle': 'Obtener tu sitio web es simple. Te guiamos en cada paso.',
    'howItWorks.step1.title': 'Cuéntanos tu idea',
    'howItWorks.step1.desc': 'Comparte lo que necesitas — un sitio para tu negocio, organización o proyecto. No se requiere conocimiento técnico.',
    'howItWorks.step2.title': 'Te guiamos',
    'howItWorks.step2.desc': 'Tu gestor de cuenta te ayuda a tomar decisiones simples de diseño y contenido. Explicamos todo claramente.',
    'howItWorks.step3.title': 'Lo construimos para ti',
    'howItWorks.step3.desc': 'Nuestro equipo crea tu sitio con cuidado. Solo apruebas los resultados — sin trabajo de tu parte.',
    'howItWorks.step4.title': 'Soporte continuo',
    'howItWorks.step4.desc': 'Tu sitio permanece online, seguro y actualizado. ¿Necesitas cambios? Solo pregunta a tu gestor de cuenta.',
    'hiw.title': 'Cómo funciona',
    'hiw.subtitle': 'Obtener tu sitio es simple. Te guiamos en cada paso — sin conocimiento técnico necesario.',
    'hiw.promise': 'Primera versión entregada en 24 horas',
    'hiw.step1.title': 'Elige tu dominio',
    'hiw.step1.desc': 'Elige un nombre para tu sitio. Verificaremos la disponibilidad y nos encargamos del registro.',
    'hiw.step2.title': 'Responde algunas preguntas',
    'hiw.step2.desc': 'Cuéntanos sobre tu negocio y qué quieres que haga tu sitio. Solo preguntas simples, nada técnico.',
    'hiw.step3.title': 'Construimos tu sitio',
    'hiw.step3.desc': 'Nuestro equipo crea un sitio hermoso y profesional basado en tus respuestas. Lo verás en 24 horas.',
    'hiw.step4.title': 'Revisar y publicar',
    'hiw.step4.desc': 'Revisa tu nuevo sitio y dinos si quieres cambios. Cuando estés satisfecho, lo publicamos.',
    'hiw.step5.title': 'Soporte humano continuo',
    'hiw.step5.desc': '¿Necesitas cambios? ¿Tienes preguntas? Tu gestor de cuenta dedicado siempre está aquí para ayudar.',
    'hiw.included.title': 'Qué está incluido',
    'hiw.included.item1': 'Diseño de sitio web hermoso y profesional',
    'hiw.included.item2': 'Hosting gratis — para siempre',
    'hiw.included.item3': 'Seguridad y actualizaciones incluidas',
    'hiw.included.item4': 'Tu propio gestor de cuenta',
    'hiw.included.item5': 'Diseño adaptado a móviles',
    'hiw.included.item6': 'Configuración SEO básica',
    'hiw.cta.title': '¿Listo para empezar?',
    'hiw.cta.subtitle': 'Describe tu idea y te guiaremos en el resto.',
    'hiw.cta.button': 'Empezar ahora — Es gratis',
    'sla.title': 'Acuerdo de servicio',
    'sla.subtitle': 'Términos claros y honestos. Queremos que sepas exactamente qué esperar de nosotros.',
    'sla.response.title': 'Tiempos de respuesta',
    'sla.response.item1': 'Consultas por email: Respondemos en 24 horas en días hábiles',
    'sla.response.item2': 'Problemas urgentes: Respuesta prioritaria en 4 horas',
    'sla.response.item3': 'Soporte por chat: En tiempo real durante horario de oficina',
    'sla.changes.title': 'Solicitudes de cambio',
    'sla.changes.item1': 'Plan Starter: 2 cambios por mes incluidos',
    'sla.changes.item2': 'Plan Pro: Cambios ilimitados incluidos',
    'sla.changes.item3': 'La mayoría de cambios se completan en 48 horas',
    'sla.scope.title': 'Qué está cubierto',
    'sla.scope.item1': 'Hosting y mantenimiento del sitio',
    'sla.scope.item2': 'Actualizaciones de seguridad y respaldos',
    'sla.scope.item3': 'Actualizaciones de contenido (texto, imágenes, diseño)',
    'sla.scope.item4': 'Soporte técnico y resolución de problemas',
    'sla.limits.title': 'Bueno saber',
    'sla.limits.item1': 'Rediseños mayores pueden requerir discusión adicional',
    'sla.limits.item2': 'Funciones complejas (e-commerce, reservas) requieren plan Pro',
    'sla.limits.item3': 'No almacenamos datos sensibles como contraseñas',
    'sla.promise.title': 'Nuestra promesa',
    'sla.promise.desc': 'Estamos aquí para hacerte la vida más fácil. Si algo no funciona, lo arreglamos. Si estás confundido, explicamos. Siempre hablarás con un humano real que se preocupa por tu éxito.',
    'services.title': 'Precios simples y honestos',
    'services.subtitle': 'Empieza completamente gratis. Mejora solo si necesitas más.',
    'services.starter.title': 'Starter',
    'services.starter.price': '$0.99',
    'services.starter.period': '/mes',
    'services.starter.feature1': 'Sitio web hermoso y profesional',
    'services.starter.feature2': '2 cambios por mes',
    'services.starter.feature3': 'Soporte humano incluido',
    'services.starter.feature4': 'Hosting incluido',
    'services.starter.feature5': 'Mantenimiento incluido',
    'services.starter.cta': 'Empezar',
    'services.pro.title': 'Pro',
    'services.pro.price': '$4.99',
    'services.pro.period': '/mes',
    'services.pro.feature1': 'Todo de Starter',
    'services.pro.feature2': 'Cambios ilimitados',
    'services.pro.feature3': 'Soporte prioritario',
    'services.pro.feature4': 'Hosting incluido',
    'services.pro.feature5': 'Mantenimiento incluido',
    'services.pro.cta': 'Mejorar a Pro',
    'services.free.title': 'Gratis para siempre',
    'services.free.price': '$0',
    'services.free.period': '/mes',
    'services.free.feature1': 'Sitio web hermoso y profesional',
    'services.free.feature2': 'Hosting gratis — siempre',
    'services.free.feature3': 'Seguridad y actualizaciones incluidas',
    'services.free.feature4': 'Tu propio gestor de cuenta',
    'services.free.feature5': 'Soporte por email amigable',
    'services.free.cta': 'Empezar gratis',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '$49',
    'services.concierge.period': '/mes',
    'services.concierge.feature1': 'Todo de Gratis',
    'services.concierge.feature2': 'Cambios ilimitados en el sitio',
    'services.concierge.feature3': 'Soporte prioritario por teléfono y chat',
    'services.concierge.feature4': 'Funciones avanzadas a pedido',
    'services.concierge.feature5': 'Integraciones personalizadas',
    'services.concierge.cta': 'Mejorar a Concierge',
    'labs.title': 'Próximamente',
    'labs.subtitle': 'Siempre estamos mejorando. Esto es lo que viene.',
    'labs.ai.title': 'Sugerencias más inteligentes',
    'labs.ai.desc': 'Te ayudaremos con ideas de diseño y consejos de contenido — impulsados por tecnología inteligente, entregados por humanos.',
    'labs.deploy.title': 'Más rápido y confiable',
    'labs.deploy.desc': 'Tu sitio cargará aún más rápido y permanecerá online pase lo que pase.',
    'labs.coming': 'En desarrollo',
    'cta.title': '¿Listo para empezar?',
    'cta.subtitle': 'Habla con una persona real hoy. Tu sitio podría estar listo esta semana — y es gratis.',
    'cta.button': 'Hablemos — Es gratis',
    'auth.login.title': 'Bienvenido de nuevo',
    'auth.login.subtitle': 'Inicia sesión para gestionar tus solicitudes de sitio',
    'auth.login.button': 'Iniciar sesión',
    'auth.signup.title': 'Crear cuenta',
    'auth.signup.subtitle': 'Únete para empezar a construir tu sitio',
    'auth.signup.button': 'Crear cuenta',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'tu@email.com',
    'auth.password': 'Contraseña',
    'auth.passwordPlaceholder': '••••••••',
    'auth.loading': 'Por favor espera...',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.signupLink': 'Crea una',
    'auth.loginLink': 'Inicia sesión',
    'auth.success.login': '¡Bienvenido de nuevo!',
    'auth.success.loginDesc': 'Has iniciado sesión correctamente.',
    'auth.success.signup': '¡Cuenta creada!',
    'auth.success.signupDesc': 'Bienvenido a Aureka Web. Ahora puedes enviar tu solicitud de sitio.',
    'auth.error.title': 'Algo salió mal',
    'auth.error.alreadyRegistered': 'Este email ya está registrado. Por favor inicia sesión.',
    'dashboard.loading': 'Cargando...',
    'dashboard.welcome': 'Tu panel',
    'dashboard.newRequest': 'Nueva solicitud de sitio',
    'dashboard.logout': 'Cerrar sesión',
    'dashboard.empty.title': 'Sin solicitudes aún',
    'dashboard.empty.desc': '¿Listo para tu primer sitio? Haz clic abajo para empezar — solo toma unos minutos.',
    'dashboard.empty.cta': 'Crear mi primer sitio',
    'dashboard.status.pending': 'Pendiente',
    'dashboard.status.inProgress': 'En progreso',
    'dashboard.status.complete': 'Completado',
    'request.step': 'Paso',
    'request.promise': 'Listo en 24 horas',
    'request.yourIdea': 'Tu idea de sitio',
    'request.step1.title': 'Cuéntanos sobre ti',
    'request.step2.title': 'Sobre tu sitio',
    'request.step3.title': 'Preferencias finales',
    'request.fullName': 'Nombre completo',
    'request.fullNamePlaceholder': 'Juan García',
    'request.email': 'Dirección de email',
    'request.emailPlaceholder': 'tu@email.com',
    'request.phone': 'Número de teléfono',
    'request.phonePlaceholder': '+34 600 000 000',
    'request.entityType': 'Eres...',
    'request.entity.individual': 'Particular',
    'request.entity.business': 'Empresa',
    'request.entity.ngo': 'ONG',
    'request.websiteGoal': '¿Qué debe hacer tu sitio?',
    'request.goal.showcase': 'Mostrar mi trabajo',
    'request.goal.services': 'Listar mis servicios',
    'request.goal.contact': 'Permitir contactarme',
    'request.goal.information': 'Compartir información',
    'request.preferredLanguage': 'Idioma del sitio',
    'request.stylePreference': 'Estilo preferido',
    'request.style.modern': 'Moderno y Limpio',
    'request.style.classic': 'Clásico y Elegante',
    'request.style.minimal': 'Minimal y Simple',
    'request.style.colorful': 'Colorido y Divertido',
    'request.consent': 'Al enviar esta solicitud, confirmo que mi información es correcta y acepto pagar las tarifas requeridas después de recibir mi sitio.',
    'request.back': 'Atrás',
    'request.next': 'Continuar',
    'request.submit': 'Enviar solicitud',
    'request.submitting': 'Enviando...',
    'request.success.title': '¡Solicitud enviada!',
    'request.success.desc': 'Hemos recibido tu solicitud. ¡Espera tu primera versión en 24 horas!',
    'request.error.title': 'Algo salió mal',
    
    // Plans - Mini Table
    'plans.badge': 'Precios Simples',
    'plans.title': 'Elige Tu Plan',
    'plans.subtitle': 'Desde páginas de aterrizaje gratuitas hasta sistemas empresariales completos. Sin cargos ocultos.',
    'plans.standard.name': 'Standard',
    'plans.standard.highlight': '1 Cambio / Mes • Subdominio Gratis',
    'plans.standard.cta': 'Empezar Gratis',
    'plans.standard.subtitle': 'Perfecto para empezar',
    'plans.pro.name': 'Pro',
    'plans.pro.highlight': 'Sitio Multi-página • Cambios Semanales',
    'plans.pro.cta': 'Lanzar Ahora',
    'plans.pro.subtitle': 'Para negocios en crecimiento',
    'plans.pro.yearlySaving': 'Ahorra 2 Meses',
    'plans.business.name': 'Business',
    'plans.business.highlight': 'Sistemas Completos • Cambios Ilimitados',
    'plans.business.cta': 'Solicitar Demo',
    'plans.business.subtitle': 'Soluciones completas',
    'plans.business.yearlySaving': 'Ahorra $100',
    'plans.popular': 'Más Popular',
    'plans.free': 'Gratis',
    'plans.month': 'mes',
    'plans.year': 'año',
    'plans.viewFull': 'Ver Comparación Completa',
    'plans.pageTitle': 'Precios y Planes Completos',
    'plans.pageSubtitle': 'Precios transparentes para cada etapa de tu negocio. Empieza gratis, escala cuando estés listo.',
    'plans.compareTitle': 'Comparación Completa de Características',
    'plans.table.feature': 'Característica',
    'plans.table.hosting': 'Hosting y Mantenimiento',
    'plans.table.hostingTip': 'Nos encargamos del hosting, actualizaciones de seguridad y respaldos.',
    'plans.table.domain': 'Nombre de Dominio',
    'plans.table.domainTip': 'La dirección de tu sitio (ej: tuempresa.com).',
    'plans.table.domainSetup': 'Configuración del Dominio',
    'plans.table.domainSetupTip': 'Cómo te ayudamos a configurar tu dominio.',
    'plans.table.buildType': 'Tipo de Construcción',
    'plans.table.buildTypeTip': 'Complejidad y tipo de sitio que construimos.',
    'plans.table.database': 'Base de Datos / Sistema',
    'plans.table.databaseTip': 'Almacenamiento para contenido dinámico, usuarios, productos.',
    'plans.table.delivery': 'Tiempo de Entrega',
    'plans.table.deliveryTip': 'Tiempo para recibir tu primera versión lista para lanzar.',
    'plans.table.scaling': 'Escalado (Ediciones)',
    'plans.table.scalingTip': 'Con qué frecuencia puedes solicitar cambios a tu sitio.',
    'plans.table.support': 'Tipo de Soporte',
    'plans.table.supportTip': 'Cómo puedes contactarnos para ayuda.',
    'plans.table.response': 'Tiempo de Respuesta',
    'plans.table.responseTip': 'Qué tan rápido respondemos a tus solicitudes.',
    'plans.table.monthly': 'Precio Mensual',
    'plans.table.yearly': 'Precio Anual',
    'plans.features.hostingFree': 'Gratis Para Siempre',
    'plans.features.hostingDb': 'Gratis + Mantenimiento de Base de Datos',
    'plans.features.hostingFull': 'Gratis + Mantenimiento de Sistema Completo',
    'plans.features.subdomain': 'Subdominio Gratis',
    'plans.features.customDomain': 'Dominio Personalizado Gratis',
    'plans.features.domainConnect': 'Conecta tu propio dominio',
    'plans.features.domainDone': 'Configuración hecha por nosotros',
    'plans.features.landingPage': 'Página de Aterrizaje Rápida',
    'plans.features.multiPage': 'Sitio Multi-página Profesional',
    'plans.features.fullSystem': 'Sistemas Completos Complejos',
    'plans.features.na': 'N/A',
    'plans.features.db5k': 'Hasta 5,000 entradas / 1 GB',
    'plans.features.db50k': 'Hasta 50,000 entradas / Escala Completa',
    'plans.features.delivery48h': '48 Horas para Lanzar',
    'plans.features.delivery5d': '48h estándar / 5 días complejo',
    'plans.features.scaling1': '1 Cambio / Mes',
    'plans.features.scalingWeek': '1 Cambio / Semana',
    'plans.features.scalingUnlimited': 'Cambios Ilimitados',
    'plans.features.supportEmail': 'Email y Chat',
    'plans.features.supportVideo': 'Email, Chat y Reuniones por Video',
    'plans.features.supportDedicated': 'Gerente Dedicado + Todos los Canales',
    'plans.features.response2d': '2 Días Hábiles',
    'plans.features.response1d': '1 Día Hábil',
    'plans.features.responseSameDay': 'Mismo Día / Prioridad',
    'addons.title': 'Add-ons Premium',
    'addons.subtitle': 'Mejora tu sitio con servicios profesionales.',
    'addons.seo': 'AUREKA SEO Boost',
    'addons.copywriting': 'Redacción Profesional',
    'addons.speedAudit': 'Auditoría de Velocidad y Rendimiento',
    'addons.branding': 'Logo y Kit de Marca',
    'addons.social': 'Integración de Redes Sociales',
    'addons.analytics': 'Configuración de Analytics y Conversión',
    'addons.extraPage': 'Página / Función Extra',
    'addons.prioritySupport': 'Upgrade de Soporte Prioritario',
    'addons.landingPage': 'Página de Aterrizaje de Marketing',
    'addons.perPage': '/página',
    'addons.perSite': '/sitio',
    'addons.oneTime': 'único',
    'addons.freeProBusiness': 'Gratis en Pro/Business',
    'plans.antiDiy.title': 'Deja de Luchar con Constructores Drag-and-Drop',
    'plans.antiDiy.desc': 'En AUREKA WEB, ofrecemos Soporte Centrado en el Humano. Envías la solicitud, entregamos la Versión Lista para Lanzar en 48 horas. Sin complicaciones, sin curva de aprendizaje, solo resultados.',
    'plans.antiDiy.delivery': 'Entrega 48h',
    'plans.antiDiy.support': 'Soporte Humano',
    'plans.versionNote': 'Listo para producción y escalable',
    'plans.cta.title': '¿Listo para Empezar?',
    'plans.cta.subtitle': 'Cuéntanos sobre tu proyecto y nos encargamos del resto. Primera versión en 48 horas.',
    'plans.cta.button': 'Lanza Tu Sitio Ahora',
    
    'footer.tagline': 'Sitios web simplificados. Soporte humano.',
    'footer.services': 'Servicios',
    'footer.company': 'Empresa',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.about': 'Nosotros',
    'footer.contact': 'Contacto',
    'footer.copyright': '© 2025 Aureka Solutions. Todos los derechos reservados.',
    'footer.ideal': 'Perfecto para pequeños negocios, ONGs y cualquiera que quiera un gran sitio sin complicaciones.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aureka-lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    const savedLang = localStorage.getItem('aureka-lang') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
