import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.howItWorks': 'How It Works',
    'nav.humanGuided': 'Our Approach',
    'nav.services': 'Plans',
    'nav.labs': 'Coming Soon',
    'nav.login': 'Login',
    'nav.getStarted': 'Get Started Free',
    'nav.theme': 'Theme',
    
    // Hero
    'hero.headline': 'Your Website.',
    'hero.headlineAccent': 'Our Expertise.',
    'hero.subheadline': 'We build beautiful, professional websites for people who don\'t want to deal with technology. You talk to a real person. We handle everything else — completely free to start.',
    'hero.cta.primary': 'Talk to Us — It\'s Free',
    'hero.cta.secondary': 'See How It Works',
    'hero.badge': 'Built for people, not techies',
    
    // Human Guided Section
    'humanGuided.title': 'You don\'t need to understand technology. We do.',
    'humanGuided.subtitle': 'Whether you\'re a small business, a non-profit, or just someone with an idea — we\'re here to help. No jargon. No confusion. Just friendly, human support.',
    'humanGuided.human.title': 'Always Human',
    'humanGuided.human.desc': 'You\'ll never talk to a robot. A real person guides you every step of the way.',
    'humanGuided.manager.title': 'Your Account Manager',
    'humanGuided.manager.desc': 'Every customer gets a dedicated human contact who knows your project inside and out.',
    'humanGuided.worry.title': 'Zero Worries',
    'humanGuided.worry.desc': 'We handle hosting, security, updates, and all the technical stuff. You focus on your business.',
    'humanGuided.support.title': 'We\'re Here to Help',
    'humanGuided.support.desc': 'Have a question? Need a change? Just ask. We respond quickly and kindly.',
    'humanGuided.quote': 'You talk to a human. We handle everything else.',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Getting your website is simple. We guide you through every step.',
    'howItWorks.step1.title': 'Tell Us Your Idea',
    'howItWorks.step1.desc': 'Share what you need — a website for your business, organization, or project. No technical knowledge required.',
    'howItWorks.step2.title': 'We Guide You',
    'howItWorks.step2.desc': 'Your account manager helps you make simple choices about design and content. We explain everything in plain language.',
    'howItWorks.step3.title': 'We Build It For You',
    'howItWorks.step3.desc': 'Our team creates your website with care. You just approve the results — no work on your end.',
    'howItWorks.step4.title': 'Ongoing Support',
    'howItWorks.step4.desc': 'Your site stays online, secure, and updated. Need changes? Just ask your account manager.',
    
    // Services
    'services.title': 'Simple, Honest Pricing',
    'services.subtitle': 'Start completely free. Upgrade only if you need more.',
    'services.free.title': 'Free Forever',
    'services.free.price': '$0',
    'services.free.period': '/month',
    'services.free.feature1': 'Beautiful, professional website',
    'services.free.feature2': 'Free hosting — always',
    'services.free.feature3': 'Security and updates included',
    'services.free.feature4': 'Your own account manager',
    'services.free.feature5': 'Friendly email support',
    'services.free.cta': 'Get Started Free',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '$49',
    'services.concierge.period': '/month',
    'services.concierge.feature1': 'Everything in Free',
    'services.concierge.feature2': 'Unlimited website changes',
    'services.concierge.feature3': 'Priority phone & chat support',
    'services.concierge.feature4': 'Advanced features on request',
    'services.concierge.feature5': 'Custom integrations',
    'services.concierge.cta': 'Upgrade to Concierge',
    
    // Labs
    'labs.title': 'Coming Soon',
    'labs.subtitle': 'We\'re always improving. Here\'s what\'s next.',
    'labs.ai.title': 'Smarter Suggestions',
    'labs.ai.desc': 'We\'ll help you with design ideas and content tips — powered by smart technology, delivered by humans.',
    'labs.deploy.title': 'Faster & More Reliable',
    'labs.deploy.desc': 'Your website will load even faster and stay online no matter what.',
    'labs.coming': 'In Development',
    
    // CTA
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Talk to a real person today. Your website could be live this week — and it\'s free.',
    'cta.button': 'Let\'s Talk — It\'s Free',
    
    // Footer
    'footer.tagline': 'Websites made simple. Support made human.',
    'footer.services': 'Services',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2025 Aureka Solutions. All rights reserved.',
    'footer.ideal': 'Perfect for small businesses, non-profits, and anyone who wants a great website without the hassle.',
  },
  ar: {
    // Navigation
    'nav.howItWorks': 'كيف يعمل',
    'nav.humanGuided': 'نهجنا',
    'nav.services': 'الباقات',
    'nav.labs': 'قريباً',
    'nav.login': 'تسجيل الدخول',
    'nav.getStarted': 'ابدأ مجاناً',
    'nav.theme': 'المظهر',
    
    // Hero
    'hero.headline': 'موقعك.',
    'hero.headlineAccent': 'خبرتنا.',
    'hero.subheadline': 'نبني مواقع احترافية وجميلة للأشخاص الذين لا يريدون التعامل مع التقنية. تتحدث مع شخص حقيقي. نحن نتولى كل شيء آخر — البداية مجانية تماماً.',
    'hero.cta.primary': 'تحدث معنا — مجاناً',
    'hero.cta.secondary': 'شاهد كيف يعمل',
    'hero.badge': 'مصمم للناس، لا للتقنيين',
    
    // Human Guided Section
    'humanGuided.title': 'لا تحتاج لفهم التقنية. نحن نفهمها.',
    'humanGuided.subtitle': 'سواء كنت شركة صغيرة أو مؤسسة خيرية أو شخصاً لديه فكرة — نحن هنا لمساعدتك. بدون مصطلحات معقدة. بدون ارتباك. فقط دعم بشري ودود.',
    'humanGuided.human.title': 'دائماً بشري',
    'humanGuided.human.desc': 'لن تتحدث أبداً مع روبوت. شخص حقيقي يرشدك في كل خطوة.',
    'humanGuided.manager.title': 'مدير حسابك',
    'humanGuided.manager.desc': 'كل عميل يحصل على شخص مخصص يعرف مشروعك تماماً.',
    'humanGuided.worry.title': 'بدون قلق',
    'humanGuided.worry.desc': 'نتولى الاستضافة والأمان والتحديثات وكل الأمور التقنية. ركز على عملك.',
    'humanGuided.support.title': 'نحن هنا للمساعدة',
    'humanGuided.support.desc': 'لديك سؤال؟ تحتاج تغيير؟ فقط اسأل. نرد بسرعة ولطف.',
    'humanGuided.quote': 'تتحدث مع إنسان. نحن نتولى كل شيء آخر.',
    
    // How It Works
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.subtitle': 'الحصول على موقعك سهل. نرشدك في كل خطوة.',
    'howItWorks.step1.title': 'أخبرنا بفكرتك',
    'howItWorks.step1.desc': 'شارك ما تحتاجه — موقع لعملك أو مؤسستك أو مشروعك. لا تحتاج معرفة تقنية.',
    'howItWorks.step2.title': 'نرشدك',
    'howItWorks.step2.desc': 'مدير حسابك يساعدك في اختيارات بسيطة للتصميم والمحتوى. نشرح كل شيء بلغة واضحة.',
    'howItWorks.step3.title': 'نبنيه لك',
    'howItWorks.step3.desc': 'فريقنا يصنع موقعك بعناية. أنت فقط توافق على النتائج — بدون عمل من طرفك.',
    'howItWorks.step4.title': 'دعم مستمر',
    'howItWorks.step4.desc': 'موقعك يبقى متاحاً وآمناً ومحدثاً. تحتاج تغييرات؟ فقط اسأل مدير حسابك.',
    
    // Services
    'services.title': 'أسعار بسيطة وصادقة',
    'services.subtitle': 'ابدأ مجاناً تماماً. قم بالترقية فقط إذا احتجت المزيد.',
    'services.free.title': 'مجاني للأبد',
    'services.free.price': '$0',
    'services.free.period': '/شهرياً',
    'services.free.feature1': 'موقع جميل واحترافي',
    'services.free.feature2': 'استضافة مجانية — دائماً',
    'services.free.feature3': 'الأمان والتحديثات مشمولة',
    'services.free.feature4': 'مدير حساب خاص بك',
    'services.free.feature5': 'دعم ودود عبر البريد',
    'services.free.cta': 'ابدأ مجاناً',
    'services.concierge.title': 'الكونسيرج',
    'services.concierge.price': '$49',
    'services.concierge.period': '/شهرياً',
    'services.concierge.feature1': 'كل ما في المجاني',
    'services.concierge.feature2': 'تعديلات غير محدودة',
    'services.concierge.feature3': 'دعم أولوية عبر الهاتف والدردشة',
    'services.concierge.feature4': 'ميزات متقدمة عند الطلب',
    'services.concierge.feature5': 'تكاملات مخصصة',
    'services.concierge.cta': 'ترقية للكونسيرج',
    
    // Labs
    'labs.title': 'قريباً',
    'labs.subtitle': 'نحن نتحسن دائماً. إليك ما هو قادم.',
    'labs.ai.title': 'اقتراحات أذكى',
    'labs.ai.desc': 'سنساعدك بأفكار للتصميم ونصائح للمحتوى — مدعومة بتقنية ذكية، تُقدم بواسطة بشر.',
    'labs.deploy.title': 'أسرع وأكثر موثوقية',
    'labs.deploy.desc': 'موقعك سيُحمّل أسرع ويبقى متاحاً مهما حدث.',
    'labs.coming': 'قيد التطوير',
    
    // CTA
    'cta.title': 'مستعد للبدء؟',
    'cta.subtitle': 'تحدث مع شخص حقيقي اليوم. موقعك يمكن أن يكون جاهزاً هذا الأسبوع — ومجاناً.',
    'cta.button': 'لنتحدث — مجاناً',
    
    // Footer
    'footer.tagline': 'مواقع بسيطة. دعم بشري.',
    'footer.services': 'الخدمات',
    'footer.company': 'الشركة',
    'footer.legal': 'قانوني',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    'footer.about': 'عنا',
    'footer.contact': 'تواصل',
    'footer.copyright': '© 2025 أوريكا سولوشنز. جميع الحقوق محفوظة.',
    'footer.ideal': 'مثالي للشركات الصغيرة والمؤسسات الخيرية وأي شخص يريد موقعاً رائعاً بدون تعقيد.',
  },
  de: {
    'nav.howItWorks': 'So funktioniert es',
    'nav.humanGuided': 'Unser Ansatz',
    'nav.services': 'Pakete',
    'nav.labs': 'Demnächst',
    'nav.login': 'Anmelden',
    'nav.getStarted': 'Kostenlos starten',
    'nav.theme': 'Design',
    'hero.headline': 'Ihre Website.',
    'hero.headlineAccent': 'Unsere Expertise.',
    'hero.subheadline': 'Wir erstellen schöne, professionelle Websites für Menschen, die sich nicht mit Technik beschäftigen möchten. Sie sprechen mit einem echten Menschen. Wir kümmern uns um alles andere — komplett kostenlos starten.',
    'hero.cta.primary': 'Sprechen Sie mit uns — Kostenlos',
    'hero.cta.secondary': 'So funktioniert es',
    'hero.badge': 'Gemacht für Menschen, nicht für Techniker',
    'humanGuided.title': 'Sie müssen Technik nicht verstehen. Wir schon.',
    'humanGuided.subtitle': 'Ob kleines Unternehmen, gemeinnützige Organisation oder jemand mit einer Idee — wir sind hier, um zu helfen. Kein Fachjargon. Keine Verwirrung. Nur freundliche, menschliche Unterstützung.',
    'humanGuided.human.title': 'Immer menschlich',
    'humanGuided.human.desc': 'Sie sprechen nie mit einem Roboter. Ein echter Mensch begleitet Sie bei jedem Schritt.',
    'humanGuided.manager.title': 'Ihr Account Manager',
    'humanGuided.manager.desc': 'Jeder Kunde erhält einen persönlichen Ansprechpartner, der Ihr Projekt in- und auswendig kennt.',
    'humanGuided.worry.title': 'Keine Sorgen',
    'humanGuided.worry.desc': 'Wir kümmern uns um Hosting, Sicherheit, Updates und alles Technische. Sie konzentrieren sich auf Ihr Geschäft.',
    'humanGuided.support.title': 'Wir helfen gerne',
    'humanGuided.support.desc': 'Haben Sie eine Frage? Brauchen Sie eine Änderung? Fragen Sie einfach. Wir antworten schnell und freundlich.',
    'humanGuided.quote': 'Sie sprechen mit einem Menschen. Wir erledigen alles andere.',
    'howItWorks.title': 'So funktioniert es',
    'howItWorks.subtitle': 'Ihre Website zu bekommen ist einfach. Wir begleiten Sie durch jeden Schritt.',
    'howItWorks.step1.title': 'Erzählen Sie uns Ihre Idee',
    'howItWorks.step1.desc': 'Teilen Sie uns mit, was Sie brauchen — eine Website für Ihr Unternehmen, Ihre Organisation oder Ihr Projekt. Keine technischen Kenntnisse erforderlich.',
    'howItWorks.step2.title': 'Wir begleiten Sie',
    'howItWorks.step2.desc': 'Ihr Account Manager hilft Ihnen bei einfachen Entscheidungen zu Design und Inhalt. Wir erklären alles verständlich.',
    'howItWorks.step3.title': 'Wir bauen es für Sie',
    'howItWorks.step3.desc': 'Unser Team erstellt Ihre Website mit Sorgfalt. Sie genehmigen nur die Ergebnisse — keine Arbeit für Sie.',
    'howItWorks.step4.title': 'Laufende Unterstützung',
    'howItWorks.step4.desc': 'Ihre Website bleibt online, sicher und aktuell. Brauchen Sie Änderungen? Fragen Sie einfach Ihren Account Manager.',
    'services.title': 'Einfache, ehrliche Preise',
    'services.subtitle': 'Starten Sie komplett kostenlos. Upgraden Sie nur, wenn Sie mehr brauchen.',
    'services.free.title': 'Für immer kostenlos',
    'services.free.price': '0€',
    'services.free.period': '/Monat',
    'services.free.feature1': 'Schöne, professionelle Website',
    'services.free.feature2': 'Kostenloses Hosting — immer',
    'services.free.feature3': 'Sicherheit und Updates inklusive',
    'services.free.feature4': 'Ihr eigener Account Manager',
    'services.free.feature5': 'Freundlicher E-Mail-Support',
    'services.free.cta': 'Kostenlos starten',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '49€',
    'services.concierge.period': '/Monat',
    'services.concierge.feature1': 'Alles aus Free',
    'services.concierge.feature2': 'Unbegrenzte Website-Änderungen',
    'services.concierge.feature3': 'Prioritäts-Support per Telefon & Chat',
    'services.concierge.feature4': 'Erweiterte Funktionen auf Anfrage',
    'services.concierge.feature5': 'Individuelle Integrationen',
    'services.concierge.cta': 'Upgrade zu Concierge',
    'labs.title': 'Demnächst',
    'labs.subtitle': 'Wir verbessern uns ständig. Das kommt als Nächstes.',
    'labs.ai.title': 'Intelligentere Vorschläge',
    'labs.ai.desc': 'Wir helfen Ihnen mit Design-Ideen und Inhaltstipps — unterstützt von intelligenter Technologie, geliefert von Menschen.',
    'labs.deploy.title': 'Schneller & Zuverlässiger',
    'labs.deploy.desc': 'Ihre Website wird noch schneller laden und immer online bleiben.',
    'labs.coming': 'In Entwicklung',
    'cta.title': 'Bereit anzufangen?',
    'cta.subtitle': 'Sprechen Sie heute mit einem echten Menschen. Ihre Website könnte diese Woche online sein — und sie ist kostenlos.',
    'cta.button': 'Lassen Sie uns reden — Kostenlos',
    'footer.tagline': 'Websites einfach gemacht. Support menschlich.',
    'footer.services': 'Dienste',
    'footer.company': 'Unternehmen',
    'footer.legal': 'Rechtliches',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'AGB',
    'footer.about': 'Über uns',
    'footer.contact': 'Kontakt',
    'footer.copyright': '© 2025 Aureka Solutions. Alle Rechte vorbehalten.',
    'footer.ideal': 'Perfekt für kleine Unternehmen, gemeinnützige Organisationen und alle, die eine tolle Website ohne Aufwand möchten.',
  },
  fr: {
    'nav.howItWorks': 'Comment ça marche',
    'nav.humanGuided': 'Notre approche',
    'nav.services': 'Forfaits',
    'nav.labs': 'Bientôt',
    'nav.login': 'Connexion',
    'nav.getStarted': 'Commencer gratuitement',
    'nav.theme': 'Thème',
    'hero.headline': 'Votre site web.',
    'hero.headlineAccent': 'Notre expertise.',
    'hero.subheadline': 'Nous créons de beaux sites professionnels pour les personnes qui ne veulent pas s\'occuper de la technologie. Vous parlez à une vraie personne. Nous gérons tout le reste — entièrement gratuit pour commencer.',
    'hero.cta.primary': 'Parlons-en — C\'est gratuit',
    'hero.cta.secondary': 'Comment ça marche',
    'hero.badge': 'Fait pour les gens, pas pour les techniciens',
    'humanGuided.title': 'Vous n\'avez pas besoin de comprendre la technologie. Nous, si.',
    'humanGuided.subtitle': 'Que vous soyez une petite entreprise, une association ou simplement quelqu\'un avec une idée — nous sommes là pour vous aider. Pas de jargon. Pas de confusion. Juste un support humain et amical.',
    'humanGuided.human.title': 'Toujours humain',
    'humanGuided.human.desc': 'Vous ne parlerez jamais à un robot. Une vraie personne vous guide à chaque étape.',
    'humanGuided.manager.title': 'Votre gestionnaire de compte',
    'humanGuided.manager.desc': 'Chaque client a un contact dédié qui connaît votre projet sur le bout des doigts.',
    'humanGuided.worry.title': 'Zéro souci',
    'humanGuided.worry.desc': 'Nous gérons l\'hébergement, la sécurité, les mises à jour et tout le technique. Vous vous concentrez sur votre activité.',
    'humanGuided.support.title': 'Nous sommes là pour aider',
    'humanGuided.support.desc': 'Une question ? Besoin d\'un changement ? Demandez simplement. Nous répondons rapidement et gentiment.',
    'humanGuided.quote': 'Vous parlez à un humain. Nous gérons tout le reste.',
    'howItWorks.title': 'Comment ça marche',
    'howItWorks.subtitle': 'Obtenir votre site web est simple. Nous vous guidons à chaque étape.',
    'howItWorks.step1.title': 'Parlez-nous de votre idée',
    'howItWorks.step1.desc': 'Dites-nous ce dont vous avez besoin — un site pour votre entreprise, association ou projet. Aucune connaissance technique requise.',
    'howItWorks.step2.title': 'Nous vous guidons',
    'howItWorks.step2.desc': 'Votre gestionnaire de compte vous aide à faire des choix simples de design et de contenu. Nous expliquons tout clairement.',
    'howItWorks.step3.title': 'Nous le construisons pour vous',
    'howItWorks.step3.desc': 'Notre équipe crée votre site avec soin. Vous approuvez simplement les résultats — aucun travail de votre côté.',
    'howItWorks.step4.title': 'Support continu',
    'howItWorks.step4.desc': 'Votre site reste en ligne, sécurisé et à jour. Besoin de changements ? Demandez à votre gestionnaire de compte.',
    'services.title': 'Tarifs simples et honnêtes',
    'services.subtitle': 'Commencez entièrement gratuitement. Passez à la version supérieure seulement si vous en avez besoin.',
    'services.free.title': 'Gratuit pour toujours',
    'services.free.price': '0€',
    'services.free.period': '/mois',
    'services.free.feature1': 'Site web beau et professionnel',
    'services.free.feature2': 'Hébergement gratuit — toujours',
    'services.free.feature3': 'Sécurité et mises à jour incluses',
    'services.free.feature4': 'Votre propre gestionnaire de compte',
    'services.free.feature5': 'Support email amical',
    'services.free.cta': 'Commencer gratuitement',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '49€',
    'services.concierge.period': '/mois',
    'services.concierge.feature1': 'Tout de Gratuit',
    'services.concierge.feature2': 'Modifications illimitées',
    'services.concierge.feature3': 'Support prioritaire téléphone & chat',
    'services.concierge.feature4': 'Fonctionnalités avancées sur demande',
    'services.concierge.feature5': 'Intégrations personnalisées',
    'services.concierge.cta': 'Passer à Concierge',
    'labs.title': 'Bientôt',
    'labs.subtitle': 'Nous nous améliorons constamment. Voici la suite.',
    'labs.ai.title': 'Suggestions plus intelligentes',
    'labs.ai.desc': 'Nous vous aiderons avec des idées de design et des conseils de contenu — propulsés par une technologie intelligente, livrés par des humains.',
    'labs.deploy.title': 'Plus rapide et plus fiable',
    'labs.deploy.desc': 'Votre site se chargera encore plus vite et restera en ligne quoi qu\'il arrive.',
    'labs.coming': 'En développement',
    'cta.title': 'Prêt à commencer ?',
    'cta.subtitle': 'Parlez à une vraie personne aujourd\'hui. Votre site pourrait être en ligne cette semaine — et c\'est gratuit.',
    'cta.button': 'Parlons-en — C\'est gratuit',
    'footer.tagline': 'Sites web simplifiés. Support humain.',
    'footer.services': 'Services',
    'footer.company': 'Entreprise',
    'footer.legal': 'Légal',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2025 Aureka Solutions. Tous droits réservés.',
    'footer.ideal': 'Parfait pour les petites entreprises, les associations et tous ceux qui veulent un super site sans tracas.',
  },
  es: {
    'nav.howItWorks': 'Cómo funciona',
    'nav.humanGuided': 'Nuestro enfoque',
    'nav.services': 'Planes',
    'nav.labs': 'Próximamente',
    'nav.login': 'Iniciar sesión',
    'nav.getStarted': 'Empezar gratis',
    'nav.theme': 'Tema',
    'hero.headline': 'Tu sitio web.',
    'hero.headlineAccent': 'Nuestra experiencia.',
    'hero.subheadline': 'Creamos sitios web hermosos y profesionales para personas que no quieren lidiar con la tecnología. Hablas con una persona real. Nosotros nos encargamos de todo lo demás — completamente gratis para empezar.',
    'hero.cta.primary': 'Hablemos — Es gratis',
    'hero.cta.secondary': 'Cómo funciona',
    'hero.badge': 'Hecho para personas, no para técnicos',
    'humanGuided.title': 'No necesitas entender la tecnología. Nosotros sí.',
    'humanGuided.subtitle': 'Ya seas un pequeño negocio, una ONG o simplemente alguien con una idea — estamos aquí para ayudar. Sin jerga. Sin confusión. Solo apoyo humano y amigable.',
    'humanGuided.human.title': 'Siempre humano',
    'humanGuided.human.desc': 'Nunca hablarás con un robot. Una persona real te guía en cada paso.',
    'humanGuided.manager.title': 'Tu gestor de cuenta',
    'humanGuided.manager.desc': 'Cada cliente tiene un contacto dedicado que conoce tu proyecto al dedillo.',
    'humanGuided.worry.title': 'Cero preocupaciones',
    'humanGuided.worry.desc': 'Nos encargamos del hosting, seguridad, actualizaciones y todo lo técnico. Tú te enfocas en tu negocio.',
    'humanGuided.support.title': 'Estamos para ayudar',
    'humanGuided.support.desc': '¿Tienes una pregunta? ¿Necesitas un cambio? Solo pregunta. Respondemos rápido y con amabilidad.',
    'humanGuided.quote': 'Hablas con un humano. Nosotros nos encargamos de todo lo demás.',
    'howItWorks.title': 'Cómo funciona',
    'howItWorks.subtitle': 'Obtener tu sitio web es simple. Te guiamos en cada paso.',
    'howItWorks.step1.title': 'Cuéntanos tu idea',
    'howItWorks.step1.desc': 'Comparte lo que necesitas — un sitio para tu negocio, organización o proyecto. No se requiere conocimiento técnico.',
    'howItWorks.step2.title': 'Te guiamos',
    'howItWorks.step2.desc': 'Tu gestor de cuenta te ayuda a tomar decisiones simples de diseño y contenido. Explicamos todo claramente.',
    'howItWorks.step3.title': 'Lo construimos para ti',
    'howItWorks.step3.desc': 'Nuestro equipo crea tu sitio con cuidado. Solo apruebas los resultados — sin trabajo de tu parte.',
    'howItWorks.step4.title': 'Soporte continuo',
    'howItWorks.step4.desc': 'Tu sitio permanece online, seguro y actualizado. ¿Necesitas cambios? Solo pregunta a tu gestor de cuenta.',
    'services.title': 'Precios simples y honestos',
    'services.subtitle': 'Empieza completamente gratis. Mejora solo si necesitas más.',
    'services.free.title': 'Gratis para siempre',
    'services.free.price': '$0',
    'services.free.period': '/mes',
    'services.free.feature1': 'Sitio web hermoso y profesional',
    'services.free.feature2': 'Hosting gratis — siempre',
    'services.free.feature3': 'Seguridad y actualizaciones incluidas',
    'services.free.feature4': 'Tu propio gestor de cuenta',
    'services.free.feature5': 'Soporte por email amigable',
    'services.free.cta': 'Empezar gratis',
    'services.concierge.title': 'Concierge',
    'services.concierge.price': '$49',
    'services.concierge.period': '/mes',
    'services.concierge.feature1': 'Todo de Gratis',
    'services.concierge.feature2': 'Cambios ilimitados en el sitio',
    'services.concierge.feature3': 'Soporte prioritario por teléfono y chat',
    'services.concierge.feature4': 'Funciones avanzadas a pedido',
    'services.concierge.feature5': 'Integraciones personalizadas',
    'services.concierge.cta': 'Mejorar a Concierge',
    'labs.title': 'Próximamente',
    'labs.subtitle': 'Siempre estamos mejorando. Esto es lo que viene.',
    'labs.ai.title': 'Sugerencias más inteligentes',
    'labs.ai.desc': 'Te ayudaremos con ideas de diseño y consejos de contenido — impulsados por tecnología inteligente, entregados por humanos.',
    'labs.deploy.title': 'Más rápido y confiable',
    'labs.deploy.desc': 'Tu sitio cargará aún más rápido y permanecerá online pase lo que pase.',
    'labs.coming': 'En desarrollo',
    'cta.title': '¿Listo para empezar?',
    'cta.subtitle': 'Habla con una persona real hoy. Tu sitio podría estar listo esta semana — y es gratis.',
    'cta.button': 'Hablemos — Es gratis',
    'footer.tagline': 'Sitios web simplificados. Soporte humano.',
    'footer.services': 'Servicios',
    'footer.company': 'Empresa',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.about': 'Nosotros',
    'footer.contact': 'Contacto',
    'footer.copyright': '© 2025 Aureka Solutions. Todos los derechos reservados.',
    'footer.ideal': 'Perfecto para pequeños negocios, ONGs y cualquiera que quiera un gran sitio sin complicaciones.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aureka-lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    const savedLang = localStorage.getItem('aureka-lang') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
